#!/usr/bin/env python3
"""Render README.md from data/*.json (called by scripts/build.py).

README.md is generated: edit data/*.json or this template, then rebuild.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import jevlib as J  # noqa: E402

AVAIL_MD = {'available': '●', 'partial': '◐', 'restricted': '◑', 'project_page_only': '◔', 'claimed_not_located': '○ claimed',
            'not_located': '○', 'not_applicable': '–', 'not_assessed': '·', 'not_attempted': '·', 'no': '○'}


def md(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ')


def main():
    d = J.load_all()
    s = J.compute_stats(d)
    cfg = d['config']
    tax = d['taxonomy']
    P = d['papers']['papers']
    C = J.by_id(d['claims']['claims'])
    T = {k: J.by_id(tax[k]) for k in ('topics', 'test_levels', 'model_relationships', 'background_groups', 'repository_types', 'method_families')}
    site = J.safe_url(cfg.get('site_url'))
    repo = J.safe_url(cfg.get('repository_url'))
    L = []
    a = L.append
    a('<!-- Generated by scripts/render-readme.py from data/*.json. Edit the data, then run `python3 scripts/build.py`. -->')
    a('')
    a('# Jev and Typed Decision Models: An Evidence Survey')
    a('')
    a(f'**An empirical survey and evidence audit of TypeSafe’s Jev and Jev-like typed decision models — calibration, selective control and open implementations.** '
      f'Data cutoff **{J.fmt_date(s["cutoff"])}** (Asia/Singapore), with a same-day incremental rerun.')
    a('')
    a(f'{s["papers"]} references ({s["core"]} core · {s["peripheral"]} peripheral · {s["background"]} background) · {s["claims"]} evidence records with locators · '
      f'{s["priority_repos"]} open resources audited · {s["findings"]} cross-cutting findings')
    a('')
    if site:
        a(f'**Website:** <{site}>')
    else:
        a('**Website:** open `index.html` in a browser, or serve the folder (see [docs/deployment.md](docs/deployment.md)). No public URL has been assigned yet.')
    a('')
    authors = [x for x in cfg.get('authors') or [] if x.get('name')]
    if authors:
        a('**Author:** ' + ', '.join(f'[{x["name"]}]({J.safe_url(x.get("url"))})' if J.safe_url(x.get('url')) else x['name'] for x in authors))
        a('')
    a('> Values are as reported by paper authors, the vendor or repository maintainers. None of the experiments was re-run for this survey, and nothing here is a unified leaderboard.')
    a('')
    a('## Contents')
    a('')
    for h in ['At a glance', 'Seven findings', 'Core studies', 'Peripheral study', 'Open implementations and evaluations', 'Background references',
              'Prior surveys', 'Method and reproducibility', 'Repository layout', 'Contributing', 'Citation and licence']:
        a(f'- [{h}](#{h.lower().replace(" ", "-")})')
    a('')
    a('## At a glance')
    a('')
    a('| Quantity | Value | Meaning |')
    a('| --- | ---: | --- |')
    rows = [
        ('Core studies', s['core'], 'Study TypeSafe Jev, a clearly identified Jev-like typed-decision implementation, or a system that materially depends on one; read in full.'),
        ('Peripheral study', s['peripheral'], 'Within reach of the scope but with contested, self-reported claims; not pooled with core evidence.'),
        ('Background references', s['background'], f'{s["background_snapshot"]} purposive seed references from the snapshot + {s["background_increment"]} added by the same-day increment; metadata/abstract depth.'),
        ('Evidence records', s['claims'], f'{s["claims_papers"]} from papers, the rest from vendor documentation and community repositories; each with locator, scope and sample size.'),
        ('arXiv queries (snapshot)', s['arxiv_queries'], f'{s["arxiv_hits"]} hits → {s["arxiv_screened"]} unique records screened.'),
        ('Increment expansion queries', s['increment_queries'], f'{s["increment_new"]} new records screened; {s["increment_added"]} added as background.'),
        ('Catalogues audited', s['catalogues'], f'{s["readmes"]} READMEs at pinned commits.'),
        ('Priority resources', s['priority_repos'], f'{s["repo_overlap"]} of them are also in the catalogue set; {s["source_files_read"]} source files read, none executed.'),
        ('GitHub discovery results', s['github_discovery'], 'De-duplicated search results at the snapshot (a discovery pool, not a census).'),
        ('Outgoing README links', s['outgoing_candidates'], 'Unverified candidates. **Not** validated Jev projects and not counted anywhere else.'),
    ]
    for q, v, m in rows:
        a(f'| {q} | {v:,} | {m} |')
    a('')
    a('## Seven findings')
    a('')
    for f in tax['findings']:
        a(f'**{f["id"]} · {f["title"]}** {f["body"]}')
        a('')
    a('## Core studies')
    a('')
    a('| Date (v1) | Study | Relationship to Jev | Test level | Headline (author-reported) | Code |')
    a('| --- | --- | --- | --- | --- | --- |')
    for p in sorted([p for p in P if p['tier'] == 'core'], key=lambda p: p['published_at'], reverse=True):
        head = C[p['claims'][0]]['headline'] if p['claims'] else ''
        code = p['openness']['code']
        code_md = f'[{AVAIL_MD[code["status"]]}]({code["url"]})' if code.get('url') else AVAIL_MD[code['status']]
        fam = ' ¹' if p.get('study_family_id') else ''
        a(f'| {p["published_at"][:10]} | [{md(p["title"])}]({p["url"]}){fam} | {md(p["relationship"])} | {T["test_levels"][p["test_level"]]["label"]} | {md(head)} | {code_md} |')
    a('')
    a('¹ Same study family (shared authors and service path); not independent replications. Code: ● located · ◐ partial · ◔ project page only · ○ not located in this review (not evidence of absence) · “claimed” = the paper says it is released.')
    a('')
    a('## Peripheral study')
    a('')
    for p in [p for p in P if p['tier'] == 'peripheral']:
        a(f'- [{md(p["title"])}]({p["url"]}) — {md(p["relationship"])} {md(p["caveats"][0])}')
    a('')
    a('## Open implementations and evaluations')
    a('')
    a('Availability at pinned commits: ● available · ◐ partial · ◑ restricted · ◔ project page only · ○ not located · – not applicable. Nothing was executed.')
    a('')
    a('| Resource | Type | Family | Code | Weights | Training | Evaluation | Raw predictions |')
    a('| --- | --- | --- | :-: | :-: | :-: | :-: | :-: |')
    for r in sorted([r for r in d['repositories']['repositories'] if 'priority' in r['sets']], key=lambda r: (r['type'], r['full_name'].lower())):
        av = r['availability']
        fam = T['method_families'][r['method_family']]['label'] if r.get('method_family') else '—'
        a(f'| [{r["full_name"]}]({r.get("readme_url") or r["url"]}) | {T["repository_types"][r["type"]]["label"]} | {fam} | '
          + ' | '.join(AVAIL_MD.get(av.get(k, 'not_assessed'), '·') for k in ('code', 'weights', 'training_code', 'evaluation', 'raw_predictions')) + ' |')
    a('')
    a('## Background references')
    a('')
    for g in tax['background_groups']:
        items = [p for p in P if p['tier'] == 'background' and p['background_group'] == g['id']]
        if not items:
            continue
        a(f'### {g["label"]}')
        a('')
        for p in sorted(items, key=lambda p: p['published_at'], reverse=True):
            venue = f' · {p["venue"]} (per arXiv {"journal ref" if p["venue_source"] == "arxiv_journal_ref" else "comment"})' if p['venue_source'] in ('arxiv_comment', 'arxiv_journal_ref') else ''
            inc = ' · *added 2026-09-23 increment*' if 'increment' in (p.get('source_record') or {}) else ''
            a(f'- [{md(p["title"])}]({p["url"]}) ({p["year"]}{venue}){inc} — {md(p["role"])}')
        a('')
    a('## Prior surveys')
    a('')
    rs = d['review-relations']['related_surveys'][0]
    a(f'A public working draft, [*{rs["title"]}*]({rs["url"]}) (dated 21 September 2026), precedes this survey and shares its separation of validity, correctness, calibration and utility. '
      'Its bibliography (at the pinned commit) contains none of the 13 core arXiv IDs reviewed here. See [docs/related-surveys.md](docs/related-surveys.md) for the dimension-by-dimension comparison. '
      'This survey makes no priority claim.')
    a('')
    a('## Method and reproducibility')
    a('')
    a('- Search protocol, screening and reading depth: [docs/methodology.md](docs/methodology.md); logs in [`data/search-runs.json`](data/search-runs.json) and [`research/`](research/).')
    a('- Evidence audit rules (measurement scopes, openness fields): [docs/evidence-audit.md](docs/evidence-audit.md). Limitations: [docs/limitations.md](docs/limitations.md).')
    a('- Survey draft: [paper/survey.md](paper/survey.md) (Markdown) and [paper/main.tex](paper/main.tex) (LaTeX; build with `latexmk -pdf main.tex` in `paper/`).')
    a('')
    a('```sh')
    a('python3 scripts/validate-data.py   # integrity and vocabulary checks')
    a('python3 scripts/build.py           # site, README, BibTeX, CSV, stats')
    a('python3 scripts/check-links.py     # link check (network)')
    a('python3 scripts/update-metadata.py # new dated arXiv increment (never overwrites the snapshot)')
    a('python3 scripts/update-github.py   # new dated GitHub discovery increment')
    a('```')
    a('')
    a('## Repository layout')
    a('')
    a('```text')
    a('data/        canonical records (papers, claims, repositories, taxonomy, relations, sources, search runs) + generated exports')
    a('site/        page template, CSS, JavaScript and lazily loaded drawer data; index.html is generated')
    a('paper/       survey manuscript (Markdown and LaTeX) and its bibliography')
    a('docs/        methodology, evidence audit, related surveys, limitations, reference study, deployment, 中文交接')
    a('research/    immutable 2026-09-23 snapshot, dated increments and the frozen editorial curation used to bootstrap data/')
    a('scripts/     validation, build, exports, link check, incremental updates')
    a('tests/       unit tests for data rules and client-side search')
    a('```')
    a('')
    a('## Contributing')
    a('')
    a('New studies, corrections, code or weights updates and reproduction reports are welcome — see [CONTRIBUTING.md](CONTRIBUTING.md). '
      'Edit `data/*.json`, never the generated files, and run the build before opening a pull request.')
    if repo:
        a(f'Open an issue: <{repo.rstrip("/")}/issues/new/choose>.')
    a('')
    a('## Citation and licence')
    a('')
    a('Citation metadata is in [CITATION.cff](CITATION.cff) (GitHub shows it under “Cite this repository”). This is a working draft: '
      'it has no DOI and has not been peer-reviewed or submitted anywhere.')
    a('')
    if authors:
        first = authors[0]
        names = ' and '.join(f'{x.get("family_names") or x["name"]}, {x.get("given_names") or ""}'.rstrip(', ') for x in authors)
        key = (first.get('family_names') or first['name'].split()[-1]).lower() + s['cutoff'][:4] + 'jevsurvey'
        a('```bibtex')
        a(f'@misc{{{key},')
        a(f'  author       = {{{names}}},')
        a('  title        = {Jev and Typed Decision Models: An Empirical Survey of Calibration, Selective Control, and Open Implementations},')
        a(f'  year         = {{{s["cutoff"][:4]}}},')
        if repo:
            a(f'  howpublished = {{\\url{{{repo}}}}},')
        a(f'  note         = {{Version {J.VERSION}, data cutoff {J.fmt_date(s["cutoff"])}. Working draft, not peer-reviewed}}')
        a('}')
        a('```')
        a('')
    a('Licences: the code (scripts, site, tests, workflows) is under the [MIT License](LICENSE); original text, figures and curated data are under '
      '[CC BY 4.0](LICENSE-CONTENT.md). Third-party material — paper metadata, quoted README facts, vendor documentation — keeps its own terms; '
      'see [NOTICE.md](NOTICE.md).')
    a('')
    (J.ROOT / 'README.md').write_text('\n'.join(L), encoding='utf-8')


if __name__ == '__main__':
    main()
