#!/usr/bin/env python3
"""Render the data-bearing documentation from data/*.json (called by scripts/build.py).

Generates docs/methodology.md, docs/related-surveys.md, docs/evidence-audit.md and data/README.md.
Hand-written docs (limitations, reference-study, deployment, handoff-zh) are not touched.
"""
import pathlib
import sys
from collections import Counter

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import jevlib as J  # noqa: E402

GEN = '<!-- Generated by scripts/render-docs.py from data/*.json. Edit the data or the script, then run scripts/build.py. -->\n\n'


def md(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ')


def methodology(d, s):
    runs = J.by_id(d['search-runs']['runs'])
    snap, inc, rej = runs['snapshot-arxiv-2026-09-23'], runs['increment-arxiv-2026-09-23T0818Z'], runs['snapshot-arxiv-rejected']
    gh, ghi = runs['snapshot-github-2026-09-23'], next((r for r in d['search-runs']['runs'] if r['id'].startswith('increment-github')), None)
    L = [GEN, '# Methodology', '',
         f'Data cutoff: **{J.fmt_date(s["cutoff"])}** (Asia/Singapore). This document is generated from `data/search-runs.json`, `data/papers.json` and `data/claims.json`.', '',
         '## 1. Questions', '',
         'RQ1 definition and lineage · RQ2 probability quality · RQ3 efficiency attribution · RQ4 selective control · RQ5 robustness · RQ6 openness and reproducibility (see `paper/survey.md` §1).', '',
         '## 2. Search', '',
         f'**Snapshot (2026-09-23).** {snap["accepted_queries"]} accepted arXiv API queries returned {snap["hits_before_dedup"]} hits and {snap["unique_screened"]} unique records after de-duplication by unversioned arXiv ID. '
         f'One compound query reported {rej["reported_total"]:,} results, was stopped after HTTP 429 and was rejected rather than screened; it was replaced by four narrow title/abstract queries. '
         '`all:` searches arXiv metadata fields, not PDF full text, so a broader recent “decision model” query was added and found a core paper that brand-name queries missed.', '',
         '| ID | Query | Hits |', '| --- | --- | ---: |']
    L += [f'| `{q["id"]}` | `{md(q["query"])}` | {q["total"] if q["total"] is not None else "—"} |' for q in snap['queries']]
    L += ['', f'Background references: 6 of the {s["background_snapshot"]} snapshot background records came from these queries; 38 were retrieved by explicit arXiv ID as a purposive seed set (not a discovery count).', '',
          f'**Same-day increment ({inc["id"].split("-", 2)[-1]}).** All {inc["accepted_rerun"]["queries"]} accepted queries were re-run; totals were '
          f'{"identical" if inc["accepted_rerun"]["reproduced_snapshot_totals"] else "different"} ({inc["accepted_rerun"]["hits_before_dedup"]} hits). '
          f'{len(inc["expansion"])} expansion queries widened the vocabulary beyond the brand name; queries returning more than 2,000 results were rejected by rule (the arXiv API treats hyphenated and multi-word phrases loosely). '
          f'All 58 bibliography IDs were refreshed: no new versions, titles or journal references.', '',
          '| ID | Query | Hits | Status |', '| --- | --- | ---: | --- |']
    L += [f'| `{q["id"]}` | `{md(q["query"])}` | {q["total"]} | {q["status"]} |' for q in inc['expansion']]
    dec = inc['decisions']
    L += ['', f'Of {inc["new_candidates"]} new records, {dec.get("include_background", 0)} were added as background references and '
          f'{dec.get("outside_core_scope", 0) + dec.get("outside_core_scope_linked_dataset", 0)} were excluded with a recorded reason '
          '(`research/increments/2026-09-23T0818Z/screening.json`). No new core study appeared: arXiv announces new submissions around 00:00 UTC, so a same-day rerun mainly verifies the snapshot.', '',
          f'**GitHub.** Five repository searches produced {gh["unique_results"]:,} unique discovery results at the snapshot; {gh["catalogues_audited"]} catalogues/guides were audited ({gh["readmes_fetched"]} READMEs at pinned commits) and {gh["priority_resources"]} priority implementation and evaluation resources were read (2 overlap). '
          f'README outgoing links ({gh["outgoing_candidates_all"]:,}) are unverified candidates and are never counted as projects.']
    if ghi:
        L += [f'The increment re-ran the searches: {ghi["unique_results"]:,} results, {ghi["new_unverified_candidates"]} new unverified candidates (none added). Watched repositories: ' +
              '; '.join(f'`{w["repo"]}` head `{w.get("head", "?")[:10]}`' for w in ghi['watched']) + '.']
    L += ['', '## 3. Eligibility', '',
          '- **Core:** evaluates TypeSafe Jev, a clearly identified Jev-like typed-decision implementation, or a system whose contribution materially depends on such decisions.',
          '- **Peripheral:** within reach of the scope but with contested or self-reported claims; kept visible, not pooled.',
          '- **Background:** adjacent methods needed for theory and baselines (classification, calibration, selective prediction, decision-focused calibration, structured output, judging, routing, label robustness), with a stated role.',
          '- **Excluded:** name collisions (Japanese encephalitis, JEPA, unrelated TypeSafe/Scala, other RLCD expansions), generic System 1/2 work without a typed-decision link.', '',
          '## 4. Screening and reading depth', '',
          f'- {s["core"]} core and {s["peripheral"]} peripheral studies: full text, key tables and limitation sections; every extracted number carries a locator.',
          f'- {s["background"]} background references: arXiv metadata and abstract (one reranker paper spot-checked in full text).',
          f'- Repositories: README at a pinned commit; {s["source_files_read"]} source files read in {s["source_repos_read"]} repositories; nothing executed.',
          '- One AI-assisted reviewer. This is not a registered protocol or a PRISMA-compliant systematic review; a second independent screener is the first open task (docs/limitations.md).', '',
          '## 5. Extraction', '',
          f'Each checkable statement is an evidence record in `data/claims.json` ({s["claims"]} records: ' +
          ', '.join(f'{v} {k.replace("_", " ")}' for k, v in sorted(s['claims_by_type'].items())) + '). '
          'Fields: subject, claim text, headline, source URL and locator, evidence type, metric/value/unit, baseline, task, sample size (or a reason), model and version (or a reason), hardware, test level, measurement scope, limitations and links to findings F1–F7.', '',
          'Measurement scopes are never pooled: single request, amortized per question, batch, end to end, simulation, author estimate, vendor claim. Test levels: model test, system test, hybrid, simulation.', '',
          'Openness is recorded as six independent fields per paper — code, weights, data, raw predictions, recomputable, independently reproduced — and seven per repository. “Not located” means not found in this review.', '',
          '## 6. Synthesis', '',
          'Findings are stated at the strength their records allow, with supporting and qualifying records listed together (site §04, `paper/survey.md` §7). Study families are synthesised once. No meta-analytic pooling is attempted: tasks, metrics and scopes are heterogeneous.', '',
          '## 7. Updating', '',
          '1. `python3 scripts/update-metadata.py` and `python3 scripts/update-github.py` write a new dated folder under `research/increments/`.',
          '2. Screen `new_candidates.json` with reasons (`screening.json`), then add accepted records to `data/`.',
          '3. `python3 scripts/validate-data.py && python3 scripts/build.py`, update `CHANGELOG.md`, and re-run `python3 scripts/check-links.py`.', '']
    return '\n'.join(L)


def related(d):
    rel = d['review-relations']
    rs = rel['related_surveys'][0]
    L = [GEN, '# Related surveys and how this one differs', '',
         f'**Prior work.** [*{rs["title"]}*]({rs["url"]}) — {rs["authors"]}; {rs["dated"]}. Status: {rs["status"]}. Checked: {rs["checked"]}',
         f'Manuscript commit: `{rs["manuscript_commit"]}`. A Git timestamp shows when a commit was made, not when the work became public; neither this survey nor the prior draft is claimed as first.', '',
         'What we credit to the prior draft: the umbrella framing of machine-native decision models, the separation of structural validity, semantic correctness, probabilistic reliability and decision utility, and a fair replication protocol with interface-level baselines. This survey adopts that separation.', '',
         'What this survey adds, and what still needs verification, is in the matrix. The empirical claims about the prior draft refer to its pinned commit and may change in later versions.', '',
         '| Dimension | Prior draft (Decisions, Not Tokens) | This survey | Basis |', '| --- | --- | --- | --- |']
    L += [f'| {md(m["dimension"])} | {md(m["prior"])} | {md(m["this_survey"])} | {md(m["evidence"])} |' for m in rel['survey_matrix']]
    L += ['', '## Adjacent surveys cited as background', '']
    names = {'2503.15850': 'uncertainty quantification and calibration in LLMs', '2502.17419': 'System 1 to System 2 reasoning LLMs',
             '2503.24377': 'efficient reasoning / reasoning economy', '2307.13565': 'decision-focused learning'}
    P = J.by_id(d['papers']['papers'], 'arxiv_id')
    for aid, topic in names.items():
        p = P[aid]
        L.append(f'- [{md(p["title"])}]({p["url"]}) — {topic}. {md(p["role"])}')
    L += ['', '## Remaining checks before claiming novelty in a submission', '',
          '1. Re-run the survey/review queries (`Q07`, `Q08`, `Q14`) and a Google Scholar / Semantic Scholar title search on the submission date.',
          '2. Re-read the prior draft at its latest commit and update the matrix.',
          '3. Phrase contributions as specific artefacts (evidence records, openness audit, protocol) rather than as priority.', '']
    return '\n'.join(L)


def audit(d, s):
    P = [p for p in d['papers']['papers'] if p['tier'] in ('core', 'peripheral')]
    C = J.by_id(d['claims']['claims'])
    tax = d['taxonomy']
    TL = J.by_id(tax['test_levels'])
    L = [GEN, '# Evidence audit', '',
         'Rules used to read and record evidence, followed by the per-study audit. Values are as reported by their sources; none were re-run.', '',
         '## Rules', '',
         '- Product, paradigm and system are separate objects: hosted TypeSafe Jev; Jev-like models, readouts and adapters; systems that use typed decisions.',
         '- Type validity, semantic correctness, calibration and downstream utility are evaluated separately.',
         '- A number is only comparable with another from the same measurement scope, task and protocol.',
         '- Same authors, shared data or the same base model do not make two results independent; study families are synthesised once.',
         '- Code visible, weights available, data available, raw predictions available, recomputable and independently reproduced are separate fields.',
         '- Where raw data are unavailable, experiments are listed as *proposed*; no result tables or intervals are generated.', '',
         '## Per-study profile', '',
         '| Study (v1 date) | Relationship | Test level | Model version | Code | Weights | Data | Predictions | Records |',
         '| --- | --- | --- | --- | --- | --- | --- | --- | ---: |']
    for p in sorted(P, key=lambda p: p['published_at']):
        mv = '; '.join(f'{v["model"]}: {v.get("version") or "not reported"}' for v in p['model_versions'])
        o = p['openness']
        L.append(f'| [{md(p["short_title"])}]({p["url"]}) ({p["published_at"][:10]}){" ¹" if p.get("study_family_id") else ""} | {md(", ".join(p["model_relationship"]))} | '
                 f'{TL[p["test_level"]]["label"]} | {md(mv)} | {o["code"]["status"]} | {o["weights"]["status"]} | {o["data"]["status"]} | {o["predictions"]["status"]} | {len(p["claims"])} |')
    L += ['', '¹ Study family `li-wang-edge-2026`.', '', '## Measurement scopes of speed and cost figures', '']
    for scope in ('single_request', 'amortized_question', 'end_to_end', 'simulation', 'author_estimate', 'vendor_claim'):
        rows = [c for c in d['claims']['claims'] if c['measurement_scope'] == scope]
        if rows:
            L.append(f'**{scope.replace("_", " ")}** — ' + '; '.join(f'{md(c["headline"])} ({c["subject"].split(":", 1)[-1]})' for c in rows))
            L.append('')
    L += ['## Corrections to the handoff notes found during this audit', '',
          '- `jev-calibration-audit`: the audit ran about 7,000 API calls in seven experiments; “11,759” is the size of the MMLU-ProX source dataset, not the audit.',
          '- 2609.23136: the “real service” result used a real image-reading service reached over **simulated** New Radio access; it is recorded as a hybrid test.',
          '- 2609.23886: the model card is `flock-io/this-that-model-1.0` (Hugging Face API 200); the PDF text shows `thisthat-model-1.0`, a line-break artefact.',
          '- Jev versions actually pinned in the core set: `jev-1.13.0` (judge, REFLEX, crash narratives), `jev-1.13` / “Jev 1.13” (JEVQA, edge, scientific decisions), `typesafe/jev1.13` via OpenRouter (CSS); not reported in three studies.', '',
          '## What would upgrade the evidence', '',
          '1. Version-pinned reruns of the option-binding and calibration results on hosted Jev with a test–retest floor.',
          '2. Same-protocol comparisons of hosted Jev, open decision models, frozen readouts and structured-output LLMs (paper §10).',
          '3. Public raw predictions for the studies that claim them (2609.26758, 2609.26550).', '']
    return '\n'.join(L)


def data_readme(d, s):
    return '\n'.join([GEN, '# Data', '',
        f'Canonical records for the Jev survey (cutoff {s["cutoff"]}). Edit these files, then run `python3 scripts/build.py`.', '',
        '| File | Contents | Edited by hand? |', '| --- | --- | --- |',
        f'| `papers.json` | {s["papers"]} records ({s["core"]} core, {s["peripheral"]} peripheral, {s["background"]} background) with verified arXiv metadata, editorial fields, openness, locators and the original snapshot fields under `source_record` | yes |',
        f'| `claims.json` | {s["claims"]} evidence records (paper, vendor and community claims) | yes |',
        f'| `repositories.json` | {s["repos_unique"]} repositories: {s["priority_repos"]} priority resources and {s["catalogues"]} catalogues/guides ({s["repo_overlap"]} in both) | yes |',
        '| `taxonomy.json` | vocabularies: stages, method families, topics, applications, relationships, test levels, scopes, evidence types, openness statuses, findings, failure modes, application cards | yes |',
        '| `review-relations.json` | study families, lineage, name collisions, prior survey and comparison matrix | yes |',
        '| `sources.json` | official vendor pages used as sources | yes |',
        '| `search-runs.json` | arXiv and GitHub search runs (snapshot and increments) | appended per increment |',
        '| `stats.json`, `references.bib`, `exports/*.csv` | generated | no |', '',
        '## Key rules', '',
        '- IDs: `arxiv:<id>` for papers, `gh:<owner/name>` (lower case) for repositories, `c-…`, `v-…`, `r-…` for claims from papers, vendor pages and repositories.',
        '- Unknown values are `null` with a `reason`; `null` is never zero.',
        '- Multi-label fields (`topics`, `stages`, `method_families`, `model_relationship`) may overlap; counts in the site explain this.',
        '- Venues are recorded only as stated in arXiv metadata (`venue_source`); `venue_verified_at` stays null until checked against proceedings.',
        '- The 4,666 README outgoing links are unverified candidates and live only in `research/snapshot-2026-09-23/repository_candidates.csv`.',
        '- CSV exports prefix cells that start with `= + - @`, tab or CR with an apostrophe (formula-injection guard).', ''])


def main():
    d = J.load_all()
    s = J.compute_stats(d)
    docs = J.ROOT / 'docs'
    docs.mkdir(exist_ok=True)
    (docs / 'methodology.md').write_text(methodology(d, s), encoding='utf-8')
    (docs / 'related-surveys.md').write_text(related(d), encoding='utf-8')
    (docs / 'evidence-audit.md').write_text(audit(d, s), encoding='utf-8')
    (J.ROOT / 'data' / 'README.md').write_text(data_readme(d, s), encoding='utf-8')


if __name__ == '__main__':
    main()
