"""Claim-level evidence records for the first canonical release (cutoff 2026-09-23).

One record = one checkable statement with its source locator, measurement scope,
sample size, model version, limitations and its relation to the survey findings
(F1–F7 in curation_2026_09_23.FINDINGS). Numbers are as reported by the source;
none was re-run by this review. Missing values are None with a reason.
"""


def C(id, subject, text, url, locator, evidence_type, metric=None, value=None, unit=None, baseline=None, task=None,
      n=None, n_unit=None, n_reason=None, model=None, version=None, version_reason=None, hardware=None,
      hardware_reason=None, test_level='model_test', scope='not_applicable', findings=(), limitations=(),
      reported_by='authors', note=None):
    return dict(
        id=id, subject=subject, claim_text=text, source_url=url, locator=locator, evidence_type=evidence_type,
        reported_by=reported_by, independently_reproduced=False,
        metric=metric, value=value, unit=unit, baseline=baseline, task=task,
        sample_size=({'n': n, 'unit': n_unit} if n is not None else {'n': None, 'reason': n_reason or 'not_reported'}),
        model=model,
        model_version=({'value': version} if version else {'value': None, 'reason': version_reason or 'not_reported'}),
        hardware=({'value': hardware} if hardware else {'value': None, 'reason': hardware_reason or 'not_reported'}),
        test_level=test_level, measurement_scope=scope,
        findings=[{'id': f, 'relation': r} for f, r in findings],
        limitations=list(limitations), note=note)


A = 'https://arxiv.org/abs/'
DOCS = 'https://docs.typesafe.ai/'
LAUNCH = 'https://typesafe.ai/blog/introducing-system-one-models-and-jev'
GH = 'https://github.com/'

CLAIMS = [
 # ---- 2609.26758 Type-Safe Is Not Error-Free ----------------------------------------------------
 C('c-26758-hosted-swap', 'arxiv:2609.26758',
   'Swapping the rubrics behind the option names no/yes changed 32.50% of the hosted model’s answers (neutral names: 2.08% and 1.67%), lowered balanced accuracy from .7127 to .5163 and AUROC from .8146 to .5806.',
   A + '2609.26758v1', '§4.6; Table 6', 'author_reported_experiment', metric='AUROC', value={'aligned': 0.8146, 'swapped': 0.5806},
   baseline='aligned name–rubric binding; neutral-name controls', task='binary workflow decisions with task-specific rubrics',
   n=1200, n_unit='items', model='hosted TypeSafe model', version_reason='not_reported', hardware_reason='not_applicable_hosted',
   findings=[('F1', 'supports')], limitations=['Hosted model is non-deterministic; observed at one point in time.', 'Contrast 30.42 pts, 95% CI [27.58, 33.33].']),
 C('c-26758-retest', 'arxiv:2609.26758',
   'Asking the aligned arm twice (300 items × 2 name pairs), the hosted model changed at most 1.33% of answers; the name swap produced 24× that test–retest floor, and at most 36.33% of probabilities repeated bit-for-bit.',
   A + '2609.26758v1', '§4.6', 'author_reported_experiment', metric='answer flip rate (test–retest)', value=0.0133,
   task='repeat identical requests', n=600, n_unit='item × name-pair repeats', model='hosted TypeSafe model', version_reason='not_reported',
   hardware_reason='not_applicable_hosted', findings=[('F1', 'supports'), ('F7', 'supports')],
   limitations=['Floor measured on a subset (300 items).']),
 C('c-26758-open-inversion', 'arxiv:2609.26758',
   'In an open ModernBERT-large marker-readout head, the same swap changed 76.92% of answers against 6.50% behind 0/1 (difference-in-differences 70.42 pts) and inverted AUROC from .9376 to .2315.',
   A + '2609.26758v1', 'Abstract; §§4.1–4.2', 'author_reported_experiment', metric='AUROC', value={'aligned': 0.9376, 'swapped': 0.2315},
   baseline='neutral names 0/1', task='binary workflow decisions', n=1200, n_unit='items',
   model='open marker-readout encoder head (not Jev)', version='one released checkpoint (name in unlocated harness)',
   hardware_reason='not_reported', findings=[('F1', 'supports'), ('F5', 'supports')],
   limitations=['This result is for an open checkpoint and must not be attributed to hosted Jev.', 'A mean-pooling span head flips 4.1× less often.']),
 C('c-26758-type-errors', 'arxiv:2609.26758',
   'The type-error rate was 0% in every condition, including those where decision accuracy collapsed; the paper shows this follows from the renormalised softmax over the declared options (Lemma 1).',
   A + '2609.26758v1', 'Abstract; §3 (Lemma 1)', 'author_reported_experiment', metric='type-error rate', value=0.0,
   task='all arms', n_reason='all_conditions', model='hosted model and two open heads', version_reason='not_reported',
   hardware_reason='not_reported', findings=[('F1', 'supports')],
   limitations=['A 0% type-error rate is a property of the read-out, so it carries no information about decision quality.']),
 C('c-26758-random-names', 'arxiv:2609.26758',
   'Replacing option names with random character strings returned flip rates to the neutral-control regime in all three families (6.86%, 11.67%, 2.02%) while aligned balanced accuracy stayed within .03 of the neutral class.',
   A + '2609.26758v1', '§4.7; Table 7', 'author_reported_experiment', metric='answer flip rate', value={'marker': 0.0686, 'span_mean': 0.1167, 'hosted': 0.0202},
   baseline='neutral names 0/1 and A/B', n=1200, n_unit='items (hosted arm)', model='three read-out families', version_reason='not_reported',
   hardware_reason='not_reported', findings=[('F1', 'qualifies')],
   limitations=['Suggests neutral identifiers as a mitigation; the mitigation itself was not evaluated in deployment.']),
 C('c-26758-multiway', 'arxiv:2609.26758',
   'On 683 multi-way questions, renaming members to neutral letters without touching descriptions changed 52.42% of answers and dropped accuracy from .5637 to .2782 (open marker head).',
   A + '2609.26758v1', '§4.5; Table 4', 'author_reported_experiment', metric='accuracy', value={'shipped': 0.5637, 'neutral_renamed': 0.2782},
   n=683, n_unit='questions', model='open marker-readout encoder head (not Jev)', version_reason='not_reported', hardware_reason='not_reported',
   findings=[('F1', 'supports')], limitations=['Pool accuracy is low (.5637); authors treat the arm as directional.']),

 # ---- 2609.26550 JEV-as-a-Judge -------------------------------------------------------------------
 C('c-26550-quality', 'arxiv:2609.26550',
   'On RewardBench Jev scored 92.2% against GPT-6’s 93.5% (paired difference −1.25 points, 95% cluster interval [−3.8, 1.5]); on HaluEval 87.5% against 86.7%. Blind adjudication of disagreements put Jev within three points of GPT-6.',
   A + '2609.26550v1', '§5 (ordinary preference and evidence-grounded factuality)', 'author_reported_experiment', metric='accuracy',
   value={'RewardBench': {'jev': 0.922, 'gpt6': 0.935}, 'HaluEval': {'jev': 0.875, 'gpt6': 0.867}}, baseline='GPT-6 Astra (strongest comparator)',
   task='pairwise preference; evidence-grounded factuality', n_reason='per_benchmark_sizes_in_paper', model='Jev', version='jev-1.13.0',
   hardware_reason='not_applicable_hosted', findings=[('F3', 'supports')],
   limitations=['Adjudication by one author on disagreement-selected items.', 'Larger gaps on derivation checking and style-adversarial pairs.']),
 C('c-26550-fee', 'arxiv:2609.26550',
   'Jev’s fee on the latency panel was 0.36% of the strongest comparator’s; the authors summarise it as about $0.04 per 1,000 judgments at 0.15 s.',
   A + '2609.26550v1', 'Abstract; §4 (latency and fees); Conclusion', 'author_reported_experiment', metric='fee ratio', value=0.0036,
   unit='fraction of comparator fee', baseline='GPT-6 Astra', n=120, n_unit='decisions (latency panel)', model='Jev', version='jev-1.13.0',
   hardware_reason='not_applicable_hosted', scope='end_to_end', findings=[('F4', 'supports')],
   limitations=['Fees are estimates from reported usage at collection-time prices, not invoices.', 'One client location, pacing and provider load.']),
 C('c-26550-cascade', 'arxiv:2609.26550',
   'A frozen two-order cascade that accepts confident Jev verdicts and escalates uncertain ones kept 99% of GPT-6’s accuracy at 57% of its fee.',
   A + '2609.26550v1', 'Abstract; §7; Conclusion', 'author_reported_experiment', metric='accuracy retained / fee', value={'accuracy_retained': 0.99, 'fee_fraction': 0.57},
   baseline='GPT-6 Astra alone', model='Jev → GPT-6 cascade', version='jev-1.13.0', hardware_reason='not_applicable_hosted',
   scope='simulation', n_reason='per_benchmark_sizes_in_paper', findings=[('F3', 'supports'), ('F4', 'qualifies')],
   limitations=['Simulated cascade fees say nothing about real cascade latency.', 'Thresholds chosen on a selection set did not transfer for every fallback.']),
 C('c-26550-confidence', 'arxiv:2609.26550',
   'Jev’s native confidence had Spearman correlation 0.971, 0.999 and 0.948 with the maximum label probability on RewardBench, JudgeBench and HaluEval, so the authors used max-probability for deferral.',
   A + '2609.26550v1', '§4 (JEV and the shared contract)', 'author_reported_experiment', metric='Spearman ρ', value={'RewardBench': 0.971, 'JudgeBench': 0.999, 'HaluEval': 0.948},
   model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted', n_reason='per_benchmark_sizes_in_paper',
   findings=[('F2', 'qualifies')], limitations=['Correlation of rankings, not a description of how confidence is computed.']),

 # ---- 2609.26532 REFLEX ----------------------------------------------------------------------------
 C('c-26532-calls', 'arxiv:2609.26532',
   'At τ = 0.5 REFLEX reached 95% success with 1.12 strong-model calls per task, against 88% and 4.10 calls for the strong-only agent — 72.7% fewer strong calls.',
   A + '2609.26532v1', 'Abstract; §5.1; Table 1', 'author_reported_experiment', metric='task success; strong calls per task',
   value={'reflex': {'success': 0.95, 'strong_calls': 1.12}, 'strong_only': {'success': 0.88, 'strong_calls': 4.10}},
   baseline='strong-only agent (B0)', task='tool-using agent tasks (REFLEX-Sim)', n=100, n_unit='frozen tasks', model='Jev + strong LLM fallback',
   version='jev-1.13.0', hardware_reason='not_applicable_hosted', test_level='system_test', scope='end_to_end',
   findings=[('F3', 'supports')], limitations=['Controlled benchmark shows ceiling effects for 2026 frontier models.']),
 C('c-26532-external', 'arxiv:2609.26532',
   'On external BFCL tasks and 300 τ-style episodes, advantages over a cheap generative cascade with self-escalation were limited where ordinary routing was already highly accurate.',
   A + '2609.26532v1', 'Abstract; external evaluation; Limitations', 'author_reported_experiment', metric='task success; cost',
   baseline='cheap generative cascade', task='BFCL; τ-style multi-turn episodes', n=300, n_unit='episodes (60 paired tasks)',
   model='Jev + strong LLM fallback', version='jev-1.13.0', hardware_reason='not_applicable_hosted', test_level='system_test',
   findings=[('F3', 'qualifies')], limitations=['Held-out validation, not a full leaderboard with multiple trials.']),
 C('c-26532-action-set', 'arxiv:2609.26532',
   'Controlled interventions showed that reliability depends on action-set size and on near-valid alternatives near authorisation boundaries.',
   A + '2609.26532v1', 'Abstract; controlled interventions', 'author_reported_experiment', task='agent decisions with varied action sets',
   model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted', n_reason='see_paper', test_level='system_test',
   findings=[('F1', 'supports'), ('F3', 'qualifies')], limitations=['Effects concentrate in authority and risk families.']),

 # ---- 2609.25845 Visual Jev -----------------------------------------------------------------------
 C('c-25845-quality', 'arxiv:2609.25845',
   'Answer-supervised post-training raised equal-weight macro accuracy across four benchmarks from 0.706 to 0.761, with the gain concentrated on the two task families represented in training.',
   A + '2609.25845v1', 'Abstract; §4; Table 2', 'author_reported_experiment', metric='macro accuracy', value={'before': 0.706, 'after': 0.761},
   baseline='untuned Qwen3-VL-4B read through its LM head', task='GQA, SNLI-VE, TextVQA, TallyQA', n_reason='per_benchmark_sizes_in_paper',
   model='Visual Jev (Qwen3-VL-4B)', version='paper v1', hardware='1× RTX 5090', findings=[('F6', 'supports')],
   limitations=['Seen-family gains; limited transfer to unseen families.']),
 C('c-25845-speed', 'arxiv:2609.25845',
   'With 32 questions per image, shared batched execution was 8.9× faster in warm amortized time than independent serial execution and 3.4× faster than batching that recomputes the prefix (5.7 ms per question; about 182 ms per 32-question batch).',
   A + '2609.25845v1', 'Abstract; §5; Limitations', 'author_reported_experiment', metric='speed-up', value={'vs_serial': 8.9, 'vs_batched_no_reuse': 3.4, 'amortized_ms': 5.7, 'batch_ms': 182},
   baseline='independent serial; batched without prefix reuse', n=32, n_unit='questions per image', model='Visual Jev (Qwen3-VL-4B)', version='paper v1',
   hardware='1× RTX 5090 (bfloat16)', scope='amortized_question', findings=[('F4', 'supports')],
   limitations=['Amortized throughput, not independent-request latency; higher peak memory; queueing excluded.']),
 C('c-25845-typed-head', 'arxiv:2609.25845',
   'A matched typed-head control offered no consistent accuracy advantage over reading candidate probabilities from the backbone’s LM head.',
   A + '2609.25845v1', 'Abstract; §5', 'author_reported_experiment', metric='accuracy', baseline='LM-head readout', model='Visual Jev variants',
   version='paper v1', hardware='1× RTX 5090', n_reason='per_benchmark_sizes_in_paper', findings=[('F5', 'supports'), ('F4', 'supports')],
   limitations=['One backbone family.']),

 # ---- 2609.24965 Scientific decisions -------------------------------------------------------------
 C('c-24965-correct-latency', 'arxiv:2609.24965',
   'Jev matched five other configurations at complete semantic correctness on 20 Choices × 5 repetitions and had the lowest observed median latency among successful responses (0.335 s; p95 0.442 s), at about $0.000060 per successful response.',
   A + '2609.24965v1', 'Abstract; §3.2; Table 1', 'author_reported_experiment', metric='semantic correctness; median latency',
   value={'median_s': 0.335, 'p95_s': 0.442, 'cost_usd_per_success': 0.00006}, baseline='eleven other configurations',
   task='source-grounded scientific Choices', n=100, n_unit='requests (20 Choices × 5)', model='Jev', version='Jev 1.13', hardware_reason='not_applicable_hosted',
   scope='single_request', findings=[('F3', 'supports'), ('F4', 'supports')],
   limitations=['Ten cases; six configurations reach complete correctness, so the set is not discriminative.']),
 C('c-24965-hidden-errors', 'arxiv:2609.24965',
   'Across three comparison models, seven wrong selections on one culture-history question changed downstream counts while preserving the correct final claim label.',
   A + '2609.24965v1', 'Abstract; §3 (correct labels can conceal wrong quantities)', 'author_reported_experiment', metric='derived-quantity errors',
   value=7, unit='wrong selections', task='Luria–Delbrück culture-history case', model='three comparison LLMs (not Jev)', version_reason='see_paper',
   hardware_reason='not_applicable_hosted', n_reason='single_case', test_level='system_test', findings=[('F6', 'supports'), ('F1', 'supports')],
   limitations=['Errors were made by comparison models; the point is about evaluation design, not about Jev.']),

 # ---- 2609.24574 CSS annotation ------------------------------------------------------------------
 C('c-24574-accuracy-cost', 'arxiv:2609.24574',
   'Jev trailed the per-task best LLM on 14 of 15 evaluation tasks, by a median 11.6 macro-F1 points, at a median 44 times lower measured cost.',
   A + '2609.24574v1', 'Abstract; §4', 'author_reported_experiment', metric='macro-F1 deficit; cost ratio', value={'tasks_trailing': '14/15', 'median_f1_deficit_pts': 11.6, 'median_cost_ratio': 44},
   baseline='per-task best of 19 LLMs', task='15 CSS classification tasks', n=7977, n_unit='items (18-task grid)', model='Jev', version='typesafe/jev1.13 (OpenRouter)',
   hardware_reason='not_applicable_hosted', scope='end_to_end', findings=[('F3', 'supports')],
   limitations=['Zero-shot protocol for every model; tasks from one established suite; older corpora may overlap with training data.'],
   note='The authors report the deficit as significant after false-discovery-rate correction.'),
 C('c-24574-ece', 'arxiv:2609.24574',
   'Jev’s median expected calibration error over the evaluation tasks was 0.157 (95% CI [0.108, 0.233]) — lower than the verbalised-confidence error of 16 of 19 LLMs but higher than three frontier Claude models (Opus 5: 0.066).',
   A + '2609.24574v1', 'Abstract; §4 (calibration); Appendix B', 'author_reported_experiment', metric='median ECE (15 equal-width bins)',
   value={'jev': 0.157, 'best_baseline': 0.066}, baseline='verbalised confidence of 19 LLMs', n=15, n_unit='tasks (≤500 items each)',
   model='Jev', version='typesafe/jev1.13 (OpenRouter)', hardware_reason='not_applicable_hosted', findings=[('F2', 'supports')],
   limitations=['Median intervals overlap.', 'Under equal-mass binning Sonnet 5 falls slightly behind Jev; Opus 5 stays ahead.']),
 C('c-24574-empathy', 'arxiv:2609.24574',
   'On the empathy task the model reported high confidence while performing near chance; the task contributes a calibration error of 0.538, and removing it lowers the median only to 0.142.',
   A + '2609.24574v1', 'Abstract; §4', 'author_reported_experiment', metric='task ECE', value=0.538, task='empathy in peer-support dialogues',
   model='Jev', version='typesafe/jev1.13 (OpenRouter)', hardware_reason='not_applicable_hosted', n_reason='per_task_size_in_paper',
   findings=[('F2', 'supports')], limitations=['One construct; the authors do not claim the failure generalises.']),
 C('c-24574-cascade', 'arxiv:2609.24574',
   'Routing low-confidence items to an LLM matched or exceeded that LLM alone at roughly a quarter to half of its measured cost; items at or above 0.9 confidence reached a median accuracy of 0.815 at 0.376 coverage.',
   A + '2609.24574v1', 'Abstract; §4 (cascades)', 'author_reported_experiment', metric='accuracy; cost fraction',
   value={'cost_fraction_range': [0.25, 0.5], 'acc_at_conf_0.9': 0.815, 'coverage_at_conf_0.9': 0.376}, baseline='LLM alone',
   model='Jev → LLM cascade', version='typesafe/jev1.13 (OpenRouter)', hardware_reason='not_applicable_hosted', n_reason='per_task_sizes_in_paper',
   scope='end_to_end', findings=[('F3', 'supports')], limitations=['Measured on the tested tasks and LLMs only.']),

 # ---- 2609.24395 JEVQA ----------------------------------------------------------------------------
 C('c-24395-study-a', 'arxiv:2609.24395',
   'Against VMAF, metadata-only JEVQA reached PLCC 0.737 (ITU-T P.1204.1: 0.733); adding bitstream data gave 0.797 and bitstream plus pixel features 0.824; a pixel-only variant failed.',
   A + '2609.24395v1', 'Abstract; §§IV–V', 'author_reported_experiment', metric='PLCC', value={'metadata': 0.737, 'bitstream': 0.797, 'bitstream_pixel': 0.824, 'p1204_1': 0.733},
   baseline='ITU-T P.1204.1; models trained on the same features', task='video quality vs VMAF', n=1936, n_unit='encodes (22 sources)',
   model='Jev reading extracted features', version='jev-1.13', hardware_reason='not_applicable_hosted', findings=[('F6', 'supports')],
   limitations=['Target is VMAF, not human MOS.', 'Trained models on the same features remain clearly ahead.']),
 C('c-24395-study-b', 'arxiv:2609.24395',
   'Against subjective MOS on AVT-VQDB-UHD-1, metadata-only JEVQA reached a correlation of 0.879, close to P.1204.1 (0.898); bitstream statistics did not help.',
   A + '2609.24395v1', 'Abstract; §V', 'author_reported_experiment', metric='correlation with MOS', value={'jevqa_metadata': 0.879, 'p1204_1': 0.898},
   baseline='ITU-T P.1204.1', task='video quality vs MOS', n=562, n_unit='processed video sequences', model='Jev reading extracted features',
   version='jev-1.13', hardware_reason='not_applicable_hosted', findings=[('F3', 'qualifies')],
   limitations=['Standard models have seen part of this database.']),

 # ---- 2609.24052 Crash narratives -----------------------------------------------------------------
 C('c-24052-scale', 'arxiv:2609.24052',
   'A first-stage screen returned answers for 499,500 Texas narratives at a cost of $25.23; the second stage coded 195,857 narratives with a 27-question schema. Cost is governed by schema size rather than narrative length.',
   A + '2609.24052v1', 'Abstract; §3; §4.1', 'author_reported_experiment', metric='records coded; cost', value={'screened': 499500, 'screen_cost_usd': 25.23, 'coded_full_schema': 195857},
   task='crash narrative coding', n=499500, n_unit='narratives screened', model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted',
   test_level='system_test', scope='end_to_end', findings=[('F4', 'supports')], limitations=['Single region and schema.']),
 C('c-24052-f1', 'arxiv:2609.24052',
   'Against 2,416 blinded human judgments the typed model reached F1 0.908; one frontier model was 0.059 higher and the other indistinguishable.',
   A + '2609.24052v1', 'Abstract; §4.3–4.4', 'author_reported_experiment', metric='F1', value={'jev': 0.908, 'frontier_gain': 0.059},
   baseline='two frontier LLMs on the same records', n=2416, n_unit='usable human judgments (effective ≈1,265)', model='Jev',
   version='jev-1.13.0', hardware_reason='not_applicable_hosted', findings=[('F3', 'supports')],
   limitations=['Sampling design gives an effective sample of about 1,265.']),
 C('c-24052-recalibration', 'arxiv:2609.24052',
   'Probabilities ranked well but overstated prevalence until recalibrated; recalibration fitted on half of the human labels reduced calibration error by a factor of about 3.3 (isotonic), with calibration varying by model rather than by paradigm.',
   A + '2609.24052v1', 'Highlights; Abstract; §4.2; Table 6', 'author_reported_experiment', metric='calibration error reduction', value=3.3, unit='× (factor)',
   baseline='raw model probabilities', n=2416, n_unit='human judgments', model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted',
   findings=[('F2', 'supports')], limitations=['Same-distribution labels; not a guarantee for new regions or schemas.']),
 C('c-24052-quantisation', 'arxiv:2609.24052',
   'Because probabilities are returned on a two-decimal grid, calibration error has a resolution floor for rare variables; the paper derives a bound that applies to any model reporting probabilities on a discrete grid.',
   A + '2609.24052v1', 'Highlights; Abstract; §3', 'author_reported_experiment', metric='resolution floor', model='Jev', version='jev-1.13.0',
   hardware_reason='not_applicable_hosted', n_reason='analytical', findings=[('F2', 'supports')],
   limitations=['Matters most for rare positives.']),
 C('c-24052-reference', 'arxiv:2609.24052',
   'Agreement with administrative coded fields understated fidelity to the narrative by a median of 0.26 in kappa.',
   A + '2609.24052v1', 'Abstract; §4.3', 'author_reported_experiment', metric='kappa gap', value=0.26, baseline='coded fields vs human narrative labels',
   model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted', n_reason='per_variable', findings=[('F6', 'supports')],
   limitations=['Specific to Texas CRIS fields.']),

 # ---- 2609.23986 Jev-Mem ----------------------------------------------------------------------------
 C('c-23986-system', 'arxiv:2609.23986',
   'On LoCoMo, Jev-Mem reached an overall LLM-as-a-Judge score of 0.777 (+11.0% relative to the strongest baseline), built memory in 158 s (6.6× faster than the fastest competing memory system) and averaged 0.93 s per query (36.7% lower than the fastest memory baseline at 1.47 s).',
   A + '2609.23986v1', 'Abstract; Experiments; Table 1', 'author_reported_experiment', metric='judge score; build time; query latency',
   value={'judge_score': 0.777, 'rel_improvement': 0.11, 'build_s': 158, 'build_speedup': 6.6, 'query_s': 0.93, 'query_reduction': 0.367},
   baseline='different strongest/fastest baseline per metric', task='long-horizon conversational memory', n_reason='benchmark_size_in_paper',
   model='Jev control plane + System-Two LLM', version_reason='not_reported', hardware_reason='not_reported', test_level='system_test', scope='end_to_end',
   findings=[('F6', 'supports')], limitations=['Gains belong to the whole system; each number has a different baseline; LLM-judge metric.']),

 # ---- 2609.23959 CallScreenBench ------------------------------------------------------------------
 C('c-23959-quality', 'arxiv:2609.23959',
   'A three-seed JevLite ensemble reached AUROC .974 with calibration error .052 on 577 turn-level decisions, non-inferior to an LLM judge (MiniMax-M3) at a pre-registered .02 margin, with no false alarms on legitimate calls and decisions 1.14 turns earlier.',
   A + '2609.23959v1', 'Abstract; results', 'author_reported_experiment', metric='AUROC; calibration error', value={'auroc': 0.974, 'ece': 0.052, 'turns_earlier': 1.14},
   baseline='LLM judge (MiniMax-M3); fine-tuned ModernBERT', task='per-turn scam screening', n=577, n_unit='turn decisions (41 scenarios)',
   model='JevLite (Qwen3-4B + LoRA; three seeds)', version='paper v1', hardware='one consumer GPU', findings=[('F5', 'supports'), ('F2', 'supports')],
   limitations=['Recipe selection had test-set exposure.', 'All callers synthetic.', 'Fine-tuned ModernBERT not significantly worse.']),
 C('c-23959-latency', 'arxiv:2609.23959',
   'JevLite took 64.5 ms per decision on one consumer GPU, 4.9× lower than the same backbone fine-tuned to generate its answer.',
   A + '2609.23959v1', 'Abstract; Table 1', 'author_reported_experiment', metric='median latency per decision', value=64.5, unit='ms',
   baseline='same Qwen3-4B backbone fine-tuned to generate', n_reason='see_paper', model='JevLite (single model)', version='paper v1',
   hardware='one consumer GPU', scope='single_request', findings=[('F4', 'supports'), ('F5', 'supports')],
   limitations=['Single-model latency; the three-model ensemble quality is a different scope.']),

 # ---- 2609.23886 this-that-model --------------------------------------------------------------------
 C('c-23886-latency', 'arxiv:2609.23886',
   'this-that-model-1.0 decided in 30.9 ms end to end on one laptop GPU and sustained 32 decisions per second, generating no output tokens.',
   A + '2609.23886v1', 'Abstract; §4', 'author_reported_experiment', metric='latency per decision', value=30.9, unit='ms', n_reason='see_paper',
   model='this-that-model-1.0 (~2B)', version='1.0', hardware='laptop RTX 5080 (per repository README)', scope='single_request',
   findings=[('F4', 'supports')], limitations=['Local timing; not comparable to hosted end-to-end latency that includes the network.']),
 C('c-23886-cohort', 'arxiv:2609.23886',
   'On a third party’s recorded cohort of 68 questions over 17 states, this-that-model scored 0.941 accuracy (Brier 0.042) against Jev’s 0.765 (0.133); the authors note the 18-point gap rests on 12 questions.',
   A + '2609.23886v1', 'Abstract; Table 1; comparison discussion', 'author_reported_experiment', metric='accuracy; Brier',
   value={'this_that': {'acc': 0.941, 'brier': 0.042}, 'jev': {'acc': 0.765, 'brier': 0.133}}, baseline='hosted Jev on the same items',
   n=68, n_unit='questions', model='this-that-model-1.0 vs Jev', version='1.0 (Jev version not stated)', hardware='laptop GPU',
   findings=[('F5', 'supports'), ('F7', 'supports')], limitations=['Small cohort; wording chosen by the third party.']),
 C('c-23886-subset', 'arxiv:2609.23886',
   'On the 2,250-question subset of the released benchmark every hosted system answered, Jev scored 0.803 against this-that-model’s 0.844 — a comparison the authors call not clean because their model was trained on those question shapes (training moved it from 0.409 to 0.844).',
   A + '2609.23886v1', 'Comparison discussion; Table 3', 'author_reported_experiment', metric='accuracy', value={'jev': 0.803, 'this_that': 0.844, 'before_training': 0.409},
   n=2250, n_unit='questions', model='this-that-model-1.0 vs Jev', version='1.0 (Jev version not stated)', hardware='laptop GPU',
   findings=[('F7', 'supports'), ('F5', 'supports')], limitations=['Training-distribution advantage for the open model.']),
 C('c-23886-cost', 'arxiv:2609.23886',
   'One pass of the 42-family internal suite cost $0.000217 of electricity (80 W at $0.30/kWh) against $10.636 and 155.2 minutes for the most accurate hosted model measured.',
   A + '2609.23886v1', 'Abstract; Table 1 notes', 'author_reported_experiment', metric='cost per suite pass', value={'this_that_usd': 0.000217, 'best_hosted_usd': 10.636, 'best_hosted_minutes': 155.2},
   baseline='most accurate hosted model', model='this-that-model-1.0', version='1.0', hardware='laptop GPU (80 W)', scope='author_estimate',
   n_reason='internal_suite_not_released', findings=[('F4', 'supports')],
   limitations=['Electricity-only marginal cost excludes hardware, operations and margin; not an API price.', 'Internal suite is not released.']),

 # ---- 2609.23136 6G edge -----------------------------------------------------------------------------
 C('c-23136-latency', 'arxiv:2609.23136',
   'With correct interpretation on all evaluated contracts, Jev reduced median decision latency by 22.4% against DeepSeek and 61.9% against Gemini.',
   A + '2609.23136v1', 'Abstract; interpretation results', 'author_reported_experiment', metric='median decision latency reduction',
   value={'vs_deepseek': 0.224, 'vs_gemini': 0.619}, baseline='DeepSeek; Gemini', n_reason='see_paper', model='Jev', version='Jev 1.13',
   hardware_reason='not_applicable_hosted', scope='single_request', findings=[('F4', 'supports')],
   limitations=['Live API timing from one location and period.']),
 C('c-23136-completion', 'arxiv:2609.23136',
   'In the real image-reading service reached over simulated NR access, Jev completed 459 of 1,080 requests correctly and on time, against 463 for DeepSeek and 435 for Qwen.',
   A + '2609.23136v1', 'Abstract; real image service results', 'author_reported_experiment', metric='correct on-time completions',
   value={'jev': 459, 'deepseek': 463, 'qwen': 435}, unit='of 1,080', baseline='DeepSeek; self-hosted Qwen', n=1080, n_unit='arrivals per method',
   model='Jev', version='Jev 1.13', hardware_reason='not_reported', test_level='hybrid', scope='end_to_end',
   findings=[('F4', 'supports'), ('F6', 'supports')], limitations=['Faster decisions did not raise completions above DeepSeek.', 'Radio access simulated.']),
 C('c-23136-modeled', 'arxiv:2609.23136',
   'In modeled update scenarios, completion rose by 3.50 and 8.35 percentage points against DeepSeek and Gemini; a direct-attribute Qwen comparison retained a 53.0% latency reduction and a 4.78-point completion gain.',
   A + '2609.23136v1', 'Abstract', 'author_reported_experiment', metric='completion gain', value={'vs_deepseek_pts': 3.50, 'vs_gemini_pts': 8.35, 'vs_qwen_pts': 4.78},
   baseline='DeepSeek; Gemini; Qwen', n=12, n_unit='trajectories per comparison', model='Jev', version='Jev 1.13', hardware_reason='not_reported',
   test_level='simulation', scope='simulation', findings=[('F4', 'qualifies')], limitations=['Simulation results; separate from the real-service counts.']),

 # ---- 2609.22753 edge replacement ----------------------------------------------------------------
 C('c-22753-latency', 'arxiv:2609.22753',
   'Across three consecutive measurement blocks, Jev reduced median client decision latency by 15.9–26.5% against a short structured-output DeepSeek deployment.',
   A + '2609.22753v1', 'Abstract; §§ on decision latency', 'author_reported_experiment', metric='median decision latency reduction',
   value={'min': 0.159, 'max': 0.265}, baseline='structured-output DeepSeek', n=3, n_unit='measurement blocks', model='Jev', version='jev-1.13',
   hardware_reason='not_applicable_hosted', scope='single_request', findings=[('F4', 'supports')], limitations=['Provider, region and time-window specific.']),
 C('c-22753-e2e-fees', 'arxiv:2609.22753',
   'Without caching, median end-to-end latency on requests both systems completed correctly was 11.1–25.3% lower and API fees per correct completion 69.0–70.6% lower; correct on-time completion matched DeepSeek in 7 of 8 conditions and exceeded it in 1.',
   A + '2609.22753v1', 'Abstract; end-to-end latency section', 'author_reported_experiment', metric='e2e latency reduction; fee per correct completion',
   value={'e2e_reduction': [0.111, 0.253], 'fee_reduction': [0.690, 0.706], 'completion_matched': '7/8'}, baseline='structured-output DeepSeek',
   n=8, n_unit='paired OCR conditions', model='Jev', version='jev-1.13', hardware='two-node OCR service', test_level='hybrid', scope='end_to_end',
   findings=[('F4', 'supports'), ('F3', 'supports')], limitations=['Caching-disabled conditions only for the latency figure.']),
 C('c-22753-cache', 'arxiv:2609.22753',
   'Applying the same repeated-request cache to all backends largely removed the latency difference: the savings are concentrated in fresh interpretation.',
   A + '2609.22753v1', 'Abstract; cache boundary section', 'author_reported_experiment', metric='latency difference with caching', baseline='cache-enabled DeepSeek',
   n_reason='see_paper', model='Jev', version='jev-1.13', hardware='two-node OCR service', test_level='hybrid', scope='end_to_end',
   findings=[('F4', 'supports')], limitations=['Cache policy specific to the tested service.']),

 # ---- 2609.25498 peripheral --------------------------------------------------------------------------
 C('c-25498-self', 'arxiv:2609.25498',
   'The authors report 92.6% macro-accuracy (95% CI 90.8–94.1%) on their own corpus of 1,150+ decisions, a 7.08 ms median latency on commodity CPU and a first-place result (81.65%) on the community JevBench board.',
   A + '2609.25498v1', 'Abstract', 'author_reported_experiment', metric='macro-accuracy; latency', value={'macro_acc': 0.926, 'latency_ms': 7.08, 'jevbench': 0.8165},
   n=1150, n_unit='decisions (author corpus)', model='werr runtime', version_reason='not_reported', hardware='commodity CPU (authors’ infrastructure)',
   scope='single_request', findings=[('F7', 'supports')], limitations=['Self-reported; leaderboard claim relies on a community submission.']),
 C('c-25498-injection', 'arxiv:2609.25498',
   'The reported 0.0% empirical prompt-injection bypass carries a 95% Wilson interval of 0.0–30.8%, which implies a very small number of evaluated vectors.',
   A + '2609.25498v1', 'Abstract', 'author_reported_experiment', metric='bypass rate', value={'point': 0.0, 'ci95': [0.0, 0.308]},
   n_reason='small_unreported_count', model='werr runtime', version_reason='not_reported', hardware_reason='not_reported',
   findings=[('F7', 'supports')], limitations=['Not a security guarantee.']),

 # ---- Vendor documentation and launch materials ---------------------------------------------------
 C('v-types', 'src:typesafe-launch',
   'TypeSafe states that Jev never makes type errors because possible outputs are defined in advance, and that its plotted 0% is analytical rather than empirical.',
   LAUNCH, '“Hallucination and Type-safety” and “Nuance”', 'vendor_documentation', metric='type-error rate', value=0.0,
   model='Jev', version_reason='launch_post', hardware_reason='not_applicable_hosted', test_level='not_applicable', scope='vendor_claim', n_reason='analytical',
   reported_by='vendor', findings=[('F1', 'qualifies')], limitations=['Schema conformance only; says nothing about semantic correctness.']),
 C('v-price-latency', 'src:typesafe-launch',
   'Launch materials report input pricing of $0.042 per million tokens with free output and an end-to-end response time of 70–500 ms, measured from the vendor’s West Coast laptops.',
   LAUNCH, 'Comparison table; “Evidence / Technical Results”', 'vendor_documentation', metric='price; latency', value={'usd_per_mtok_input': 0.042, 'latency_ms': [70, 500]},
   model='Jev', version='jev-1.13.0 (docs/models)', hardware_reason='not_applicable_hosted', test_level='not_applicable', scope='vendor_claim', n_reason='not_reported',
   reported_by='vendor', findings=[('F4', 'qualifies')], limitations=['Vendor notes it cannot prove the price is not subsidised.', 'Region- and load-dependent.']),
 C('v-workflow-evals', 'src:typesafe-launch',
   'The “193.6× faster, 444.6× cheaper” headline comes from the vendor’s workflow evaluations, whose reference answers average two external frontier models; the vendor expects these to be on the higher end of real-world gains and notes the workflows were written by its capabilities team.',
   LAUNCH, '“Workflow evals” and “Nuance”', 'vendor_reported_result', metric='speed and cost ratios', value={'faster': 193.6, 'cheaper': 444.6},
   model='Jev', version_reason='launch_post', hardware_reason='not_applicable_hosted', test_level='not_applicable', scope='vendor_claim', n=4, n_unit='published workflows',
   reported_by='vendor', findings=[('F4', 'qualifies'), ('F7', 'supports')], limitations=['Reference answers are model outputs, not ground truth.', 'Possible selection bias acknowledged by the vendor.']),
 C('v-confidence', 'src:typesafe-docs-confidence',
   'Choice and Score answers return a probability for every option or level and a confidence value computed from that distribution; Noul answers return only the probability of yes. The documentation calls confidence a convenient statistic and recommends thresholds tested on the user’s own data.',
   DOCS + 'confidence', '“Confidence is derived from the probabilities”', 'vendor_documentation', model='Jev', version='jev-1.13.0',
   hardware_reason='not_applicable_hosted', test_level='not_applicable', n_reason='documentation', reported_by='vendor', findings=[('F2', 'qualifies')],
   limitations=['The exact statistic is not specified in the prose; the interactive demo’s formula is labelled as how the demo computes it.']),
 C('v-calibration-group', 'src:typesafe-docs-system-one',
   'The vendor states that calibration is measured across groups of predictions and does not guarantee that an individual answer is correct.',
   DOCS + 'concepts/system-one', '“How it differs from an LLM”', 'vendor_documentation', model='System One models', version_reason='documentation',
   hardware_reason='not_applicable_hosted', test_level='not_applicable', n_reason='documentation', reported_by='vendor', findings=[('F2', 'supports')]),
 C('v-text-only', 'src:typesafe-docs-models',
   'jev-1.13.0 accepts text only (a string, JSON object or array of text values); images, audio and video must be pre-processed into text or structured fields. English is the primary training language.',
   DOCS + 'models', 'Current models table; State', 'vendor_documentation', model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted',
   test_level='not_applicable', n_reason='documentation', reported_by='vendor', findings=[('F5', 'qualifies')],
   limitations=['Visual Jev and JEVQA do not change this: one is an independent model, the other feeds text features.']),
 C('v-jaggedness', 'src:typesafe-docs-jaggedness',
   'The vendor’s jev-1.13 “jaggedness” page lists known failure modes: literal reading, arithmetic and counting, date comparison, indirection, large irrelevant state, adversarial content, contradictory instructions and criteria, structural invariants, and generation.',
   DOCS + 'model-jaggedness/jev-1.13', 'Failure-mode table (last reviewed 2026-09-17)', 'vendor_documentation', model='Jev', version='jev-1.13',
   hardware_reason='not_applicable_hosted', test_level='not_applicable', n_reason='documentation', reported_by='vendor', findings=[('F1', 'supports'), ('F3', 'supports')],
   limitations=['A boundary statement by the vendor, not a neutral evaluation.']),
 C('v-versioning', 'src:typesafe-docs-models',
   'Aliases jev-latest and jev-preview both pointed to jev-1.13.0 at the time of review; the vendor advises pinning the versioned ID when thresholds were tuned to a specific version.',
   DOCS + 'models', 'Aliases', 'vendor_documentation', model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted', test_level='not_applicable',
   n_reason='documentation', reported_by='vendor', findings=[('F7', 'qualifies')]),
 C('v-no-per-account', 'src:typesafe-docs-models',
   'Jev is not fine-tuned or LoRA-adapted with customer data; it is trained with RLCD and the same weights serve every account. Architecture and training data are not documented.',
   DOCS + 'models', '“Customizing Jev”', 'vendor_documentation', model='Jev', version='jev-1.13.0', hardware_reason='not_applicable_hosted',
   test_level='not_applicable', n_reason='documentation', reported_by='vendor', findings=[('F5', 'supports')]),

 # ---- Community repositories (author-reported; not re-run; not peer-reviewed) ---------------------
 C('r-calibration-audit', 'gh:jujumilk3/jev-calibration-audit',
   'Seven API-only experiments (about 7,000 calls) report that removing the abstain option drove accuracy on unanswerable items from 0.950 to 0.000 at 0.79 confidence, that a Noul and a two-option Choice over the same question differed by 0.125 on average, that 50 identical requests gave 15 distinct answers, and that option order produced no argmax flips in 400 trials.',
   GH + 'jujumilk3/jev-calibration-audit/blob/daab9e2c2d5d5683bf07f3482deb653c26856219/README.md', 'README “Results” table', 'community_report',
   metric='several', value={'abstain_removed_acc': [0.950, 0.0], 'noul_vs_choice_gap': 0.125, 'distinct_answers_of_50': 15, 'order_flips_of_400': 0},
   n=7000, n_unit='API calls (approx.)', model='Jev (API)', version_reason='not_reported', hardware_reason='not_applicable_hosted',
   reported_by='repository author', findings=[('F1', 'supports'), ('F2', 'supports')],
   limitations=['Community report; not peer-reviewed; not re-run by this review.', 'Earlier summaries misread the 11,759 items of the MMLU-ProX source set as the audit size.']),
 C('r-assay-001', 'gh:jourdanlabs/assay-001',
   'A pre-registered audit reports Jev’s chosen-option probabilities as calibrated on CLINC150 (ECE 0.0204) but systematically overconfident on Banking77 (ECE 0.0936), with zero type errors across 8,576 responses.',
   GH + 'jourdanlabs/assay-001/blob/b7f71053a88025a5af80af00801c5ce725c9547d/README.md', 'README verdict', 'community_report',
   metric='ECE', value={'CLINC150': 0.0204, 'Banking77': 0.0936}, n=8576, n_unit='responses', model='Jev (API)', version_reason='see_repository',
   hardware_reason='not_applicable_hosted', reported_by='repository author', findings=[('F2', 'supports'), ('F1', 'supports')],
   limitations=['Community report; protocol frozen before queries per the README; not re-run by this review.']),
 C('r-acento', 'gh:marcosmartinez/jev-acento',
   'With English instructions and a Spanish state, jev-1.13.0 lost 3.0–6.4 accuracy points on all four datasets (XNLI, PAWS-X, MASSIVE, Belebele) across 3,200 paired items and 19,200 calls; ECE roughly doubled on the two hardest tasks.',
   GH + 'marcosmartinez/jev-acento/blob/7e007b4c2bd552471b56eff035f9a3df7593f9fe/README.md', 'README “Findings”', 'community_report',
   metric='accuracy change', value={'min_pp': -3.0, 'max_pp': -6.4}, n=3200, n_unit='paired items', model='Jev', version='jev-1.13.0',
   hardware_reason='not_applicable_hosted', reported_by='repository author', findings=[('F2', 'supports')],
   limitations=['Community report; pre-registered per README; not re-run by this review.']),
 C('r-ood', 'gh:scienthoon/jev-ood-calibration',
   'On a rule-based task whose label is not recoverable from the text, the chosen level averaged 0.74 probability and a temperature of about 3.4 was needed to make probabilities honest; the returned probabilities were quantised to 0.01 and the gateway exposed no model version.',
   GH + 'scienthoon/jev-ood-calibration/blob/914d87ab16517f14e833cff63d73b51235b14bd6/README.md', 'README “Results” and synthetic-task section', 'community_report',
   metric='refit temperature', value=3.4, n=900, n_unit='synthetic items (+3,721 public items)', model='Jev via Vercel AI Gateway (typesafe-ai/jev)',
   version_reason='gateway_exposes_no_version', hardware_reason='not_applicable_hosted', reported_by='repository author',
   findings=[('F2', 'supports'), ('F7', 'supports')], limitations=['Unpinned model alias; post-hoc temperature diagnostic.']),
 C('r-synthetic-survey', 'gh:jjd-lab/jev-synthetic-survey',
   'Playing 300 survey respondents, jev-1.13.0 asked through Noul led GPT-4.1 on all six distribution measures, but asked through a two-option Choice it trailed on the distribution gap (0.1985 vs 0.1789): the primitive changes the conclusion.',
   GH + 'jjd-lab/jev-synthetic-survey/blob/8dbb40db3a69e4d174b5962ffef3bdb8ee7e7a68/README.md', 'README summary', 'community_report',
   metric='distribution gap', value={'jev_choice': 0.1985, 'gpt41': 0.1789}, n=24596, n_unit='answered cells per arm', model='Jev', version='jev-1.13.0',
   hardware_reason='not_applicable_hosted', reported_by='repository author', findings=[('F1', 'supports')],
   limitations=['“Survey” here means a questionnaire study, not a literature review.', 'Community report; not re-run.']),
 C('r-anyjev', 'gh:nokia-applied-research/anyjev',
   'For a frozen Qwen3-8B on BANKING77 (20-way, 300 items), label-free permutation calibration reduced answer flips under option reversal from 0.230 to 0.073 and ECE from 0.240 to 0.184; with 100–500 labels ECE fell to 0.095 and the share decidable at ≤5% error rose from 7.7% to 52.0%.',
   GH + 'nokia-applied-research/AnyJev/blob/54f1b3533639f52a406941706a4fdf08b2193589/README.md', 'README “What it does” table', 'community_report',
   metric='flip rate; ECE; auto-decidable share', value={'flips': [0.230, 0.073], 'ece_L0': 0.184, 'ece_L1': 0.095, 'auto_decidable': [0.077, 0.520]},
   n=300, n_unit='test items', model='frozen Qwen3-8B via AnyJev', version='README at commit 54f1b35', hardware_reason='not_reported',
   reported_by='repository authors', findings=[('F2', 'supports'), ('F3', 'supports'), ('F5', 'supports')],
   limitations=['Point estimate at n=300; wide interval per README.']),
 C('r-localjev', 'gh:githubnext/localjev',
   'LocalJev returns Jev-shaped responses by asking a model for JSON probabilities, validating, retrying and normalising them; its README states this is wire-compatible but not mathematically equivalent to a logit read.',
   GH + 'githubnext/localjev/blob/3f23e36e1a3bff46c7e83e8e3781d3512bc82021/README.md', 'README “Why a bridge is needed”', 'code_inspection',
   model='DiffusionGemma via chat completions', version='README at commit 3f23e36', hardware_reason='not_applicable', test_level='not_applicable',
   n_reason='documentation', reported_by='this review (README)', findings=[('F5', 'supports')]),
 C('r-semif', 'gh:theoleecj/semif',
   'SemIf (formerly OpenJev) reproduces the interface pattern with a frozen open model’s option-token probabilities and states that it does not reproduce Jev’s undisclosed model or training.',
   GH + 'TheoLeeCJ/SemIf/blob/1f2dea3e25379f9dfc98cb83c324f00ab5deda37/README.md', 'README introduction', 'code_inspection',
   model='frozen Qwen3.5-4B (and others)', version='README at commit 1f2dea3', hardware_reason='not_applicable', test_level='not_applicable',
   n_reason='documentation', reported_by='this review (README)', findings=[('F5', 'supports')]),
 C('r-kev', 'gh:jaredpalmer/kev',
   'Kev states that it follows an architecture described in a third-party blog post about Jev; that description is community speculation, not a disclosure by TypeSafe.',
   GH + 'jaredpalmer/kev/blob/557598fced1dada75dfbf36ed144dce309ac6ceb/README.md', 'README introduction', 'code_inspection',
   model='Kev (Qwen3.5 base)', version='README at commit 557598f', hardware_reason='not_applicable', test_level='not_applicable',
   n_reason='documentation', reported_by='this review (README)', findings=[('F5', 'supports')]),
]


# Compact headlines (<= ~90 characters) for tables, tooltips and the manuscript.
HEADLINES = {
    'c-26758-hosted-swap': 'Hosted Jev AUROC .8146 → .5806 after name–rubric swap; 0% type errors',
    'c-26758-retest': 'Test–retest floor ≤1.33% answer flips; swap = 24× the floor',
    'c-26758-open-inversion': 'Open marker head: AUROC .9376 → .2315 (inversion), 76.92% flips',
    'c-26758-type-errors': 'Type-error rate 0% in every condition, by construction',
    'c-26758-random-names': 'Random-string names return flips to the neutral regime (2–12%)',
    'c-26758-multiway': 'Multi-way: neutral renaming flips 52.42%; accuracy .5637 → .2782',
    'c-26550-quality': 'RewardBench 92.2% vs 93.5%; HaluEval 87.5% vs 86.7% (GPT-6)',
    'c-26550-fee': '0.36% of the comparator’s fee; ≈$0.04 per 1,000 judgments at 0.15 s',
    'c-26550-cascade': 'Frozen two-order cascade: 99% of GPT-6 accuracy at 57% of its fee',
    'c-26550-confidence': 'Native confidence ~ max probability (Spearman .948–.999)',
    'c-26532-calls': '95% success with 1.12 strong calls/task vs 88% and 4.10 (−72.7%)',
    'c-26532-external': 'BFCL / τ-style: limited edge over a cheap generative cascade',
    'c-26532-action-set': 'Reliability depends on action-set size and near-valid alternatives',
    'c-25845-quality': 'Macro accuracy 0.706 → 0.761 after post-training (seen families)',
    'c-25845-speed': '8.9× vs serial, 3.4× vs no-reuse batch; 5.7 ms/question amortized',
    'c-25845-typed-head': 'Typed head: no consistent gain over LM-head readout',
    'c-24965-correct-latency': 'Full semantic correctness; median 0.335 s, p95 0.442 s',
    'c-24965-hidden-errors': '7 wrong selections changed counts but not the final label',
    'c-24574-accuracy-cost': 'Behind best LLM on 14/15 tasks (−11.6 F1) at 44× lower cost',
    'c-24574-ece': 'Median ECE 0.157 vs 0.066 for the best (verbalised) LLM',
    'c-24574-empathy': 'Empathy: confident near chance; task ECE 0.538',
    'c-24574-cascade': 'Low-confidence routing matches the LLM at ¼–½ of its cost',
    'c-24395-study-a': 'PLCC vs VMAF: 0.737 (metadata) → 0.824 (+bitstream, pixel)',
    'c-24395-study-b': 'Correlation with MOS 0.879 vs P.1204.1 0.898',
    'c-24052-scale': '499,500 narratives screened for $25.23; 195,857 fully coded',
    'c-24052-f1': 'F1 0.908 vs 2,416 human judgments; one frontier LLM +0.059',
    'c-24052-recalibration': 'Recalibration on held-out labels cut calibration error ~3.3×',
    'c-24052-quantisation': 'Two-decimal probabilities set a calibration-error floor',
    'c-24052-reference': 'Coded fields understate narrative fidelity by 0.26 kappa',
    'c-23986-system': 'LoCoMo judge 0.777 (+11.0%); build 158 s; 0.93 s/query',
    'c-23959-quality': 'JevLite ensemble AUROC .974, ECE .052; no false alarms',
    'c-23959-latency': '64.5 ms/decision; 4.9× faster than same backbone generating',
    'c-23886-latency': '30.9 ms per decision on one laptop GPU; 32 decisions/s',
    'c-23886-cohort': '68 questions: 0.941 (Brier .042) vs Jev 0.765 (.133); gap = 12 items',
    'c-23886-subset': '2,250 questions: 0.844 vs Jev 0.803 — on the open model’s training shapes',
    'c-23886-cost': '$0.000217 electricity per suite pass vs $10.636 for a hosted model',
    'c-23136-latency': 'Median decision latency −22.4% vs DeepSeek, −61.9% vs Gemini',
    'c-23136-completion': 'Correct & on time: Jev 459, DeepSeek 463, Qwen 435 of 1,080',
    'c-23136-modeled': 'Simulated completion +3.50 / +8.35 points',
    'c-22753-latency': 'Median client decision latency −15.9% to −26.5%',
    'c-22753-e2e-fees': 'No cache: e2e −11.1–25.3%; fees per correct completion −69–71%',
    'c-22753-cache': 'Repeated-request caching largely removes the latency gap',
    'c-25498-self': 'Self-reported 92.6% macro-accuracy, 7.08 ms on CPU, “#1” on JevBench',
    'c-25498-injection': '“0% bypass” with a 95% interval up to 30.8%',
    'v-types': 'No type errors by construction; plotted 0% is analytical',
    'v-price-latency': '$0.042 / M input tokens; 70–500 ms end to end (vendor)',
    'v-workflow-evals': '193.6× faster, 444.6× cheaper on vendor workflow evals',
    'v-confidence': 'Confidence = a statistic of the returned distribution',
    'v-calibration-group': 'Calibration is a group property, not a per-answer guarantee',
    'v-text-only': 'Text-only input; English is the primary training language',
    'v-jaggedness': 'Vendor-listed failure modes for jev-1.13',
    'v-versioning': 'Aliases point to jev-1.13.0; pin versions when tuning thresholds',
    'v-no-per-account': 'Same weights for all accounts; architecture undisclosed',
    'r-calibration-audit': 'Abstain removed: acc 0.95 → 0; Noul vs Choice differ by 0.125',
    'r-assay-001': 'ECE 0.0204 (CLINC150) vs 0.0936 (Banking77); 0 type errors',
    'r-acento': 'Spanish state: −3.0 to −6.4 accuracy points on 4 datasets',
    'r-ood': 'Unknowable-rule task: temperature ≈3.4 needed; 0.01 quantisation',
    'r-synthetic-survey': 'Noul vs Choice framing reverses the comparison with GPT-4.1',
    'r-anyjev': 'Frozen Qwen3-8B: order flips 0.230 → 0.073; auto-decidable 7.7% → 52%',
    'r-localjev': 'Wire-compatible, not a logit read: probabilities are generated',
    'r-semif': 'Reproduces the interface pattern, not Jev’s model or training',
    'r-kev': 'Architecture follows third-party speculation, not a disclosure',
}
for _c in CLAIMS:
    _c['headline'] = HEADLINES[_c['id']]
