"""Editorial curation for the first canonical release (cutoff 2026-09-23).

This module is the frozen editorial input that scripts/bootstrap-from-snapshot.py
merges with the immutable research snapshot (research/snapshot-2026-09-23/) to
produce data/*.json. After bootstrapping, data/*.json is the single source of
truth; edit it directly and run `python3 scripts/build.py`.

Every number below was checked against the full text of the cited paper (or the
commit-pinned README for repository claims) during the 2026-09-23 review.
Locators refer to paper v1. Nothing here was independently re-run.
"""

CUTOFF = '2026-09-23'

# ---------------------------------------------------------------------------
# Taxonomy: an analytical organisation for this survey, not the architecture of
# any commercial system. Categories may overlap; counts use multi-label rules.
# ---------------------------------------------------------------------------
STAGES = [
    dict(id='contract', n='01', label='Decision contract',
         question='What exactly is being asked, and what may the answer be?',
         covers='State, typed question, option names, rubrics, levels, cardinality, abstain options.',
         evidence='Type validity; name and order invariance; closed-set failure when the right option is missing.'),
    dict(id='readout', n='02', label='Inference & readout',
         question='How is a distribution over the declared options produced?',
         covers='Hosted service, encoder heads, frozen or fine-tuned decoder readouts, diffusion reads, generative adapters.',
         evidence='Same-backbone ablations; readout geometry; what is and is not disclosed.'),
    dict(id='probability', n='03', label='Probability & calibration',
         question='What does a returned probability or confidence mean, and for which population?',
         covers='Native vs verbalised probabilities, confidence statistics, ECE/Brier/NLL, recalibration, quantisation.',
         evidence='Per-task reliability, high-confidence errors, recalibration on held-out labels.'),
    dict(id='control', n='04', label='Selective control',
         question='When should software act, ask, escalate or abstain?',
         covers='Thresholds, risk–coverage, cascades to stronger models, human review budgets.',
         evidence='Coverage at fixed risk; escalation rate; thresholds chosen on a separate selection set.'),
    dict(id='use', n='05', label='Downstream use',
         question='Does the whole workflow get better, cheaper or faster?',
         covers='End-task success, end-to-end latency, cost per correct completion, derived quantities.',
         evidence='System-level baselines; module attribution; matched measurement scope.'),
]

METHOD_FAMILIES = [
    dict(id='hosted_service', n='A', label='Hosted System One service',
         principle='A closed, hosted model returns a distribution over declared options for each typed question about a shared text state.',
         representatives=['TypeSafe Jev (jev-1.13.0)'],
         disclosed='Interface, primitives, pricing, limits, versioning and known failure modes are documented; architecture, training data and the exact confidence statistic are not.',
         boundary='Black-box evaluation only; the served model can change behind aliases; text-only input.',
         repos=['gh:typesafe-ai/typesafe-sdk-python', 'gh:typesafe-ai/typesafe-sdk-js']),
    dict(id='encoder_head', n='B', label='Encoder decision heads',
         principle='A bidirectional encoder reads state, question and options together; a head scores each option and a softmax is taken over the legal set.',
         representatives=['Laya (ModernBERT-large, mmBERT-base)', 'open marker-readout and span-mean heads audited in 2609.26758'],
         disclosed='Weights and inference code for Laya; the readout geometry (marker token vs span mean) changes name sensitivity.',
         boundary='Short context windows; option-name polarity can dominate the rubric; adjacent to GLiClass, SetFit and NLI zero-shot classifiers.',
         repos=['gh:nandhakishorm/laya']),
    dict(id='frozen_decoder_readout', n='C', label='Frozen decoder option readout',
         principle='An unmodified causal LM is prompted once and the next-token logits of single-token option labels are renormalised over the declared options.',
         representatives=['SemIf (formerly OpenJev)', 'AnyJev (permutation and label-based calibration)'],
         disclosed='Fully open and training-free; the natural low-cost baseline for any trained decision model.',
         boundary='Raw logits are order-sensitive and poorly calibrated without correction; label tokenisation matters.',
         repos=['gh:theoleecj/semif', 'gh:nokia-applied-research/anyjev']),
    dict(id='finetuned_decoder', n='D', label='Fine-tuned decoder decision models',
         principle='A decoder is adapted (LoRA or full fine-tuning) so that a designated position or pointer head yields calibrated option probabilities in one pass.',
         representatives=['Kev', 'decider', 'this-that-model-1.0', 'NanoJev', 'Bespoke Nimble', 'JevLite (2609.23959)', 'Visual Jev (2609.25845)'],
         disclosed='Several release weights, training code and evaluation data; lineages exist (this-that-model is adapted from decider-2b).',
         boundary='Gains may come from task coverage in training; derived checkpoints are not independent methods.',
         repos=['gh:jaredpalmer/kev', 'gh:mapika/decider', 'gh:flock-io/this-that-model', 'gh:tianyucodings/nanojev', 'gh:bespokelabsai/nimble', 'gh:guanxuyu-sv/visual-jev']),
    dict(id='diffusion_readout', n='E', label='Diffusion structured readout',
         principle='A discrete diffusion LM is seeded with the answer template; after one denoising step, the distribution at each answer slot is read directly.',
         representatives=['djev (vLLM example server)', 'OpenJev on DiffusionGemma (razorback16)'],
         disclosed='Open servers with a Jev-compatible wire API; depends on request extensions proposed in an unmerged vLLM PR.',
         boundary='A different mechanism from last-token decoder readout; custom entropy-based confidence.',
         repos=['gh:mmastrac/djev', 'gh:razorback16/openjev']),
    dict(id='generative_adapter', n='F', label='Generative & constrained adapters',
         principle='A general LLM is asked (often under JSON-schema constraints) to emit a decision and probabilities, which are validated and returned in Jev-shaped responses.',
         representatives=['system-one-adapter-python (official, for comparisons)', 'LocalJev'],
         disclosed='Wire compatibility for controlled comparisons; probabilities are generated or verbalised, not read from logits.',
         boundary='Interface compatibility is not mechanism equivalence; retries, parsing and self-reported probabilities remain.',
         repos=['gh:typesafe-ai/system-one-adapter-python', 'gh:githubnext/localjev']),
]

TOPICS = [
    dict(id='interface-semantics', label='Interface semantics', desc='Option names, rubric binding, primitive choice (Noul vs Choice), schema wording.'),
    dict(id='calibration', label='Calibration', desc='Reliability of probabilities and confidence; recalibration; quantisation.'),
    dict(id='selective-control', label='Selective control', desc='Thresholds, escalation, cascades, abstention and review budgets.'),
    dict(id='efficiency', label='Efficiency & cost', desc='Latency scopes, batching, prefix sharing, caching and cost accounting.'),
    dict(id='robustness', label='Robustness', desc='Perturbations, distribution shift, language variation and adversarial input.'),
    dict(id='open-models', label='Open implementations', desc='Open-weight or training-free Jev-like models and readouts.'),
    dict(id='evaluation-methodology', label='Evaluation methodology', desc='Reference labels, invalid-output handling, test–retest noise, attribution.'),
    dict(id='structured-output', label='Structured output', desc='Constrained decoding, schema validity and forced answers.'),
    dict(id='judging', label='Judging & reward', desc='LLM-as-a-judge and reward models as comparators or uses.'),
    dict(id='routing', label='Routing & cascades', desc='Model routing and cascade cost–quality trade-offs.'),
    dict(id='classification', label='Classification', desc='General discriminative and zero-shot classifiers as baselines.'),
    dict(id='agents', label='Agents', desc='Decisions inside tool-using or memory-bearing agents.'),
    dict(id='multimodal', label='Multimodal inputs', desc='Visual or video decisions and how the input reaches the model.'),
]

APPLICATIONS = [
    dict(id='workflow-decisions', label='Workflow decisions'),
    dict(id='judging', label='Model judging'),
    dict(id='agent-control', label='Agent control'),
    dict(id='agent-memory', label='Agent memory'),
    dict(id='annotation', label='Annotation & coding'),
    dict(id='scientific-workflow', label='Scientific workflows'),
    dict(id='video-quality', label='Video quality'),
    dict(id='fraud-screening', label='Scam-call screening'),
    dict(id='edge-orchestration', label='Edge orchestration'),
    dict(id='visual-qa', label='Visual questions'),
    dict(id='triage', label='Edge triage'),
]

MODEL_RELATIONSHIPS = [
    dict(id='commercial_jev', label='Commercial Jev', desc='Evaluates or uses TypeSafe’s hosted Jev.'),
    dict(id='independent_jev_like', label='Independent Jev-like', desc='Builds or evaluates an open or independent typed-decision model or readout.'),
    dict(id='downstream_system', label='Downstream system', desc='A larger system whose contribution depends on typed decisions.'),
    dict(id='adjacent_method', label='Adjacent method', desc='Background: classifiers, calibration, selective prediction, structured output, judging, routing.'),
]

TEST_LEVELS = [
    dict(id='model_test', label='Model test', desc='Decisions scored directly against labels.'),
    dict(id='system_test', label='System test', desc='A full workflow or agent is scored on its end outcome.'),
    dict(id='hybrid', label='Hybrid', desc='Live model calls combined with simulated components.'),
    dict(id='simulation', label='Simulation', desc='Outcomes produced by a simulator.'),
    dict(id='not_applicable', label='Not applicable', desc='Documentation or design claims.'),
]

MEASUREMENT_SCOPES = [
    dict(id='single_request', label='Single request', desc='Latency or cost of one independent decision request.'),
    dict(id='amortized_question', label='Amortized per question', desc='Batch time divided by the number of questions sharing a context.'),
    dict(id='batch', label='Batch / throughput', desc='Total time or throughput of a batch.'),
    dict(id='end_to_end', label='End to end', desc='Includes network, queueing, retries or downstream execution.'),
    dict(id='simulation', label='Simulated', desc='Timing or completion produced by a simulator.'),
    dict(id='author_estimate', label='Author estimate', desc='Derived or modelled figures (e.g. electricity-only cost).'),
    dict(id='vendor_claim', label='Vendor claim', desc='First-party figure without an independent protocol.'),
    dict(id='not_applicable', label='Not applicable', desc='Quality or calibration claims.'),
]

EVIDENCE_TYPES = [
    dict(id='author_reported_experiment', label='Author-reported experiment'),
    dict(id='vendor_documentation', label='Vendor documentation'),
    dict(id='vendor_reported_result', label='Vendor-reported result'),
    dict(id='community_report', label='Community report (repository)'),
    dict(id='code_inspection', label='Code/README inspection by this review'),
]

OPENNESS_FIELDS = [
    dict(id='code', label='Code visible'),
    dict(id='weights', label='Weights available'),
    dict(id='data', label='Data available'),
    dict(id='predictions', label='Raw predictions available'),
    dict(id='recomputable', label='Results recomputable'),
    dict(id='reproduction', label='Independently reproduced'),
]
OPENNESS_STATUSES = {
    'available': 'Located and publicly accessible.',
    'partial': 'Some components public; others missing or restricted.',
    'restricted': 'Exists but access is limited by licence or data agreement.',
    'claimed_not_located': 'The paper says it is released; this review did not locate it.',
    'not_located': 'Not located in this review (not evidence that it does not exist).',
    'project_page_only': 'Only a project page or result files are public.',
    'not_applicable': 'Does not apply (e.g. weights of a hosted commercial service).',
    'not_attempted': 'This review did not attempt independent reproduction.',
    'not_assessed': 'Not assessed in this review.',
    'no': 'Cannot be recomputed from the materials located in this review.',
}

# Cross-cutting findings used to organise the evidence synthesis. Each claim in
# data/claims.json links to one or more findings as supports / qualifies / challenges.
FINDINGS = [
    dict(id='F1', short='Valid ≠ correct', title='A type-valid answer can still be the wrong answer.',
         body='Typed interfaces remove parse and schema failures by construction. They say nothing about whether the model read the option the way the author intended: rebinding option names to rubrics, removing an abstain option or asking through a different primitive can move answers while the type-error rate stays at zero.'),
    dict(id='F2', short='Measurable ≠ calibrated', title='A native probability makes calibration measurable, not guaranteed.',
         body='Every call returns a distribution, so reliability can be audited on each run. Measured calibration varies by task and construct, confident errors occur, probabilities are quantised to two decimals, and recalibration fitted on in-distribution labels helps substantially. Calibration is a property to verify per workload, not a certificate.'),
    dict(id='F3', short='First pass, then escalate', title='The most consistent use is a bounded first pass with confidence-gated escalation.',
         body='Across judging, annotation and agent control, the typed model is usually cheaper and faster but not the most accurate component. Gains appear when uncertain cases are routed to a stronger model or a person, thresholds are chosen on separate data, and cheap generative cascades are included as baselines.'),
    dict(id='F4', short='Fast is not one number', title='Speed and cost claims decompose into different mechanisms and scopes.',
         body='Single-request latency, per-question amortized time, batch throughput, end-to-end task time, simulated timing, electricity-only cost and API bills are different quantities. Prefix sharing, batching and caching can explain as much as the readout does. None of the figures can be pooled into a single leaderboard.'),
    dict(id='F5', short='Compatible ≠ equivalent', title='Interface compatibility is not mechanism equivalence.',
         body='Open projects reproduce the request and response shape with encoders, frozen or fine-tuned decoders, diffusion reads or prompted generators. Their probabilities come from different mechanisms, they differ in what is released, and none establishes the architecture of the commercial model.'),
    dict(id='F6', short='Attribute the gain', title='System-level gains need module-level attribution and the right reference.',
         body='Memory systems, orchestration pipelines and scientific workflows improve for many reasons at once. Attribution requires ablations, matched baselines and references that measure what the workflow reuses (derived quantities, narrative-grounded labels) rather than only final labels.'),
    dict(id='F7', short='Young, clustered evidence', title='The evidence base is young, clustered and unreplicated.',
         body='Thirteen core preprints appeared within four days, each as a single version; two share a study family; many community results are self-reported; several comparisons rest on a handful of items or on test-set-informed choices. None of the core results has been independently reproduced.'),
]

# Background grouping (44 purposively selected references)
BACKGROUND_GROUPS = [
    dict(id='classification', zh='分类器与通用判别', label='Classifiers & general discrimination'),
    dict(id='calibration', zh='概率校准与不确定性', label='Calibration & uncertainty'),
    dict(id='selective', zh='选择性预测与升级', label='Selective prediction & deferral'),
    dict(id='decision-calibration', zh='决策相关校准与效用', label='Decision-focused calibration & utility'),
    dict(id='structured-output', zh='结构化输出与高效推理', label='Structured output & efficient inference'),
    dict(id='judging', zh='模型评判与奖励', label='Judging & reward models'),
    dict(id='routing', zh='路由与推理资源分配', label='Routing & reasoning budgets'),
    dict(id='label-robustness', zh='标签、格式与语义鲁棒性', label='Label, format & semantic robustness'),
]


def _o(code_s, weights_s, data_s, predictions_s, recomputable_s, reproduction_s='not_attempted', **notes):
    """Openness record: six independent fields, each with a status and optional note/url.

    Positional arguments are statuses; keyword arguments `<field>=` and `<field>_url=` add notes.
    """
    rec = {}
    for field, status in [('code', code_s), ('weights', weights_s), ('data', data_s), ('predictions', predictions_s),
                          ('recomputable', recomputable_s), ('reproduction', reproduction_s)]:
        rec[field] = {'status': status}
        if notes.get(field):
            rec[field]['note'] = notes[field]
        if notes.get(field + '_url'):
            rec[field]['url'] = notes[field + '_url']
    return rec


# ---------------------------------------------------------------------------
# Core (13) and peripheral (1) papers. Keys are unversioned arXiv IDs.
# ---------------------------------------------------------------------------
PAPERS = {
 '2609.26758': dict(
    short_title='Type-Safe Is Not Error-Free',
    relationship='Black-box evaluation of hosted Jev alongside two open-weight Jev-like encoder decision heads.',
    summary='Holds question, state, rubric wording and the set of option names fixed and changes only which name is bound to which rubric. The study separates type validity (0% type errors by construction) from name invariance, ranking quality and test–retest noise across three read-out families.',
    task='Binary workflow decisions with task-specific rubrics (1,200 items over 4 predicates), plus generic-rubric, multi-way (683 questions) and random-name arms.',
    datasets=['1,200 binary workflow decisions (4 predicates)', '683 multi-way questions', '1,800-item pooled corpus (span-mean head)'],
    baselines=['aligned (as-shipped) name–rubric binding', 'neutral names (0/1, A/B)', 'random character-string names', 'hosted-model test–retest floor'],
    models=['Open ModernBERT-large marker-readout head', 'Open DeBERTa-v3-large span-mean head', 'Hosted TypeSafe model (version not stated)'],
    main_finding='Rebinding the rubrics behind no/yes lowered hosted Jev’s AUROC from .8146 to .5806 and flipped 32.50% of its answers (neutral names: ~2%; 24× its test–retest floor) while type errors stayed at 0%. The steeper .94→.23 inversion comes from an open marker head, not from Jev.',
    caveats=['The .9376→.2315 AUROC inversion belongs to an open marker-readout checkpoint, not to hosted Jev.',
             'One released checkpoint per open read-out geometry; English only.',
             'The hosted model is a non-deterministic black box observed at one point in time; no model version is pinned.',
             'The multi-way arm rests on a pool with shipped accuracy .5637 and is directional.',
             'Mitigations (neutral identifiers; randomising names in training) are proposed, not evaluated.'],
    survey_use='Report type validity, name invariance, ranking quality and test–retest noise as separate quantities; order permutation and name–rubric rebinding are different interventions.',
    topics=['interface-semantics', 'robustness', 'open-models', 'evaluation-methodology'],
    stages=['contract', 'readout'], method_families=['hosted_service', 'encoder_head'], applications=['workflow-decisions'],
    model_relationship=['commercial_jev', 'independent_jev_like'], test_level='model_test',
    model_versions=[dict(model='TypeSafe hosted model', version=None, reason='not_reported', note='Queried over HTTP; vendor pages fetched 2026-09-22.')],
    openness=_o('claimed_not_located', 'not_located', 'claimed_not_located', 'claimed_not_located', 'no',
                code='The paper states that evaluation code, per-item probabilities and raw hosted responses are released with it; no uniquely matching public repository was located.',
                weights='The two open checkpoints are said to be on the Hugging Face Hub, with names deferred to the unlocated harness.'),
    locator='Abstract; §§3, 4.1–4.7, 6–7; Tables 6–7', priority='P0'),
 '2609.26550': dict(
    short_title='JEV-as-a-Judge',
    relationship='Evaluates hosted jev-1.13.0 as a model judge against sixteen generative and reward-model judges.',
    summary='Asks whether a decision-only judge can provide an economical first pass and identify when stronger evaluation is needed. Native label probabilities are compared with verbalised probabilities, invalid outputs count as errors, and frozen accept-or-escalate cascades are tested.',
    task='Pairwise preference, evidence-grounded factuality and final-answer adjudication (RewardBench, JudgeBench, HaluEval; 1,312-item extension), with RewardBench 2 and RM-Bench diagnostics.',
    datasets=['RewardBench', 'JudgeBench', 'HaluEval', 'RewardBench 2 (sample)', 'RM-Bench (sample)', '150 saved final-answer replies', '120-decision latency panel'],
    baselines=['13 hosted judges incl. GPT-6 Astra, Claude Sonnet 5, Gemini 3.1 Pro', 'local Qwen3-32B and Qwen3.5-27B', 'PairRM-hf', 'Skywork-Reward-V2-Qwen3-8B'],
    models=['TypeSafe Jev (jev-1.13.0)'],
    main_finding='On ordinary preference and evidence-grounded factuality Jev stayed within three points of the strongest judge (GPT-6 Astra) at 0.36% of its fee; a frozen two-order cascade kept 99% of GPT-6’s accuracy at 57% of its fee.',
    caveats=['Gaps widen when a judgment requires checking a derivation or resisting an elaborately written wrong answer.',
             'The 1,312-item extension was added after preliminary results were known; multi-family analyses are exploratory.',
             'Human adjudication covers 183 disagreement-selected items, completed by one author.',
             'Latency comes from a 120-decision panel at one client location; simulated cascade fees say nothing about real cascade latency.',
             'Single-order cascades are post hoc; only the frozen two-order policies test a pre-specified rule.'],
    survey_use='Separate native from verbalised probabilities; judge pairs in both orders; count invalid outputs as errors; report fees and real cascade latency separately.',
    topics=['judging', 'selective-control', 'calibration', 'efficiency', 'evaluation-methodology'],
    stages=['probability', 'control', 'use'], method_families=['hosted_service'], applications=['judging'],
    model_relationship=['commercial_jev'], test_level='model_test',
    model_versions=[dict(model='Jev', version='jev-1.13.0', note='Price at collection: $0.042 per million input tokens.')],
    openness=_o('claimed_not_located', 'not_applicable', 'partial', 'claimed_not_located', 'no',
                code='The paper points to an anonymous supplementary package; no public package was confirmed. A same-named GitHub project cannot be matched automatically.',
                data='Public benchmarks; licensing of the saved replies needs review before redistribution (per the paper).'),
    locator='Abstract; §§4–5, 7; Conclusion; Limitations; Appendices I, L', priority='P0'),
 '2609.26532': dict(
    short_title='REFLEX with Jev',
    relationship='Uses hosted jev-1.13.0 as a typed decision layer inside an LLM agent, calling a strong LLM when confidence is low or generation is required.',
    summary='Compares strong-only, cheap-generative-cascade and Jev-gated agents on a frozen 100-task benchmark, adds controlled interventions on action-set size and near-valid alternatives, and checks external BFCL and τ-style tasks.',
    task='Tool-using agent decisions on REFLEX-Sim (100 frozen tasks); BFCL function selection; 300 τ-style episodes over 60 paired tasks.',
    datasets=['REFLEX-Sim (100 tasks)', 'BFCL', 'τ-style held-out episodes (300)'],
    baselines=['strong-only agent (B0)', 'cheap generative cascade with self-escalation', 'three strong-fallback families'],
    models=['TypeSafe Jev (jev-1.13.0)', 'strong LLM fallbacks'],
    main_finding='At threshold τ = 0.5, REFLEX reached 95% success with 1.12 strong-model calls per task, against 88% and 4.10 calls for the strong-only agent (72.7% fewer strong calls).',
    caveats=['Only one proprietary decision model is tested.',
             'On BFCL ordinary routing is near-saturated; on τ-style episodes a cheap generative cascade remains competitive.',
             'The τ evaluation is a 300-episode held-out validation, not a full leaderboard; API costs are dated snapshots.',
             'Action-set size and ambiguity effects concentrate in authority and risk families.'],
    survey_use='Compare Jev-only, strong-only, cheap-cascade and Jev-cascade arms on end-task success and the actual number of strong-model calls.',
    topics=['agents', 'selective-control', 'efficiency', 'routing'],
    stages=['control', 'use'], method_families=['hosted_service'], applications=['agent-control'],
    model_relationship=['commercial_jev', 'downstream_system'], test_level='system_test',
    model_versions=[dict(model='Jev', version='jev-1.13.0')],
    openness=_o('not_located', 'not_applicable', 'partial', 'not_located', 'no',
                code='No uniquely matching author repository located; community projects named “reflex” are unrelated.',
                data='Uses public BFCL / τ-style tasks; REFLEX-Sim release not located.'),
    locator='Abstract; §5.1; Table 1; external evaluation; Limitations', priority='P0'),
 '2609.25845': dict(
    short_title='Visual Jev',
    relationship='An independent vision–language decision model. It is not a TypeSafe product and is not evidence that hosted Jev accepts images.',
    summary='Encodes an image and public context once, runs isolated question suffixes as a batch, and reads candidate probabilities from the backbone’s LM head. The design separates four effects: model quality, readout, prefix sharing and batching.',
    task='Forced-choice visual questions on GQA, SNLI-VE, TextVQA and TallyQA with Qwen3-VL-4B (8B extension) on one RTX 5090.',
    datasets=['GQA', 'SNLI-VE', 'TextVQA', 'TallyQA'],
    baselines=['untuned backbone read through its LM head', 'matched typed-head control', 'independent serial execution', 'batched execution without prefix reuse'],
    models=['Visual Jev (Qwen3-VL-4B post-trained)'],
    main_finding='Post-training raised equal-weight macro accuracy from 0.706 to 0.761; with 32 questions per image, shared batched execution was 8.9× faster (warm, amortized) than independent serial calls and 3.4× faster than batching that recomputes the prefix.',
    caveats=['5.7 ms is amortized: a 32-question batch completes in about 182 ms. It is not the latency of an independent request.',
             'Accuracy gains concentrate on the two task families represented in training.',
             'A matched typed head showed no consistent accuracy advantage over the LM-head readout.',
             'Single-machine study on a consumer GPU; queueing latency is excluded.'],
    survey_use='Attribute speed to prefix sharing and batching and quality to adaptation — not to a special head. Classify separately from text-feature approaches such as JEVQA.',
    topics=['multimodal', 'efficiency', 'open-models'],
    stages=['readout', 'use'], method_families=['finetuned_decoder'], applications=['visual-qa'],
    model_relationship=['independent_jev_like'], test_level='model_test',
    model_versions=[dict(model='Visual Jev (Qwen3-VL-4B based)', version='paper v1')],
    openness=_o('project_page_only', 'not_located', 'available', 'partial', 'partial',
                code='The repository carries the project page and result JSON; its README states that the full evaluation tree is not in the repository.',
                code_url='https://github.com/guanxuyu-sv/Visual-Jev/blob/2c3451b20d282545aa7372aa78b06fc795804738/README.md',
                data='Public benchmarks.', predictions='Result files behind the paper tables are published on the project page.'),
    locator='Abstract; §§4–5; Tables 2–3; Limitations; linked repository README', priority='P0'),
 '2609.24965': dict(
    short_title='Jev for Scientific Decisions',
    relationship='Evaluates hosted Jev 1.13 as a semantic decision component; arithmetic stays in code, following the vendor’s documented division of labour.',
    summary='Twenty source-grounded Choices across ten scientific cases decide which relation governs a downstream calculation. Semantic selections, derived quantities and final claim labels are scored separately.',
    task='20 Choices in 10 scientific cases; 12 model configurations; 5 repetitions each.',
    datasets=['10 curated scientific cases (20 Choices)'],
    baselines=['eleven other model configurations (frontier and open-weight LLMs)'],
    models=['TypeSafe Jev 1.13'],
    main_finding='Jev matched five other configurations at complete semantic correctness and had the lowest observed median latency among successful responses (0.335 s; p95 0.442 s). Seven wrong selections by comparison models changed downstream counts while leaving the final label correct.',
    caveats=['A tiny development collection; repetitions do not add independent cases.',
             'Every model-routed reference label is “inconsistent”, so balanced claim decisions are untested.',
             'All observed semantic errors concern a single Choice.'],
    survey_use='Score intermediate relations, derived quantities and final labels together: a correct label can hide a wrong process.',
    topics=['evaluation-methodology', 'efficiency'],
    stages=['contract', 'use'], method_families=['hosted_service'], applications=['scientific-workflow'],
    model_relationship=['commercial_jev'], test_level='system_test',
    model_versions=[dict(model='Jev', version='Jev 1.13', note='Patch version not stated.')],
    openness=_o('not_located', 'not_applicable', 'partial', 'not_located', 'no',
                code='Protocol and appendices are detailed; no public code repository confirmed.',
                data='Case materials are described in appendices.'),
    locator='Abstract; §3.2; Table 1; Limitations', priority='P1'),
 '2609.24574': dict(
    short_title='Decision Models for CSS Annotation',
    relationship='Evaluates hosted Jev and open-weight decision models against 19 LLMs under one zero-shot protocol.',
    summary='Replicates an 18-task computational-social-science suite to ask whether decision models can serve as annotators. Accuracy, measured cost and calibration are reported together, and low-confidence routing to an LLM is tested.',
    task='18 CSS classification tasks (7,977 items: 3 for selection, 15 for evaluation); an appendix extends to open decision models.',
    datasets=['Ziems et al. (2024) CSS suite'],
    baselines=['19 frontier and open-weight LLMs (verbalised confidence)', 'open decision models: Laya, decider-0.8b/2b, SemIf, Bespoke-Nimble-9B, Qwen3-0.6B RLCD'],
    models=['TypeSafe Jev (typesafe/jev1.13 via OpenRouter)', 'open-weight decision models'],
    main_finding='Jev trailed the per-task best LLM on 14 of 15 tasks (median −11.6 macro-F1) at a median 44× lower measured cost. Its median ECE (0.157) beat the verbalised confidence of 16 of 19 LLMs but not three frontier Claude models (best 0.066). Routing low-confidence items to an LLM matched or exceeded the LLM alone at a quarter to half of its cost.',
    caveats=['High confidence is not reliable across constructs: on empathy the model is confident while performing near chance (task calibration error 0.538).',
             'Verbalised LLM confidence and native probabilities are different signals; baselines that decline to estimate are excluded from calibration.',
             'Older public corpora may overlap with training data; the overlap is unknown.'],
    survey_use='A core paper that brand-name searches miss; the clearest accuracy–cost–calibration trade-off in the set.',
    topics=['calibration', 'selective-control', 'efficiency', 'open-models', 'classification'],
    stages=['probability', 'control', 'use'], method_families=['hosted_service', 'encoder_head', 'frozen_decoder_readout', 'finetuned_decoder'], applications=['annotation'],
    model_relationship=['commercial_jev', 'independent_jev_like'], test_level='model_test',
    model_versions=[dict(model='Jev', version='typesafe/jev1.13', note='Accessed via the OpenRouter decisions API (reference [26] of the paper).')],
    openness=_o('available', 'not_applicable', 'available', 'available', 'available',
                code='Author replication package with analysis scripts; pilot_jev.py was read (not executed).',
                code_url='https://github.com/hazemibrahim97/decision-models-css/blob/45b71ce8403eababae18cc51dda5ecb6d67e05e4/README.md',
                data='Public releases of the Ziems et al. suite and upstream sources.',
                predictions='Complete per-call records are released.',
                recomputable='Aggregates can be recomputed from released records; not executed by this review.'),
    locator='Abstract; §§3–5; Appendix B; Ethics and Limitations; repository', priority='P0'),
 '2609.24395': dict(
    short_title='JEVQA',
    relationship='Hosted text-only Jev reads video metadata, bitstream statistics and pixel-derived features; the video itself is never an input.',
    summary='Tests a general decision model as a zero-shot video-quality predictor from structured features and compares it with the standardised ITU-T P.1204 models and with regressors trained on the same features.',
    task='Study A: 1,936 AV1/H.264/HEVC/VP9 encodes of 22 sources scored against VMAF. Study B: 562 encodes from AVT-VQDB-UHD-1 with subjective MOS.',
    datasets=['CRF ladders of 22 sources (Study A)', 'AVT-VQDB-UHD-1 (Study B)'],
    baselines=['ITU-T P.1204.1', 'models trained on the same features'],
    models=['TypeSafe Jev (jev-1.13)'],
    main_finding='With metadata only, JEVQA reached PLCC 0.737 against VMAF (P.1204.1: 0.733), rising to 0.797 with bitstream data and 0.824 with bitstream plus pixel features; against MOS it reached 0.879 (P.1204.1: 0.898).',
    caveats=['Study A’s target is VMAF, not human MOS.',
             'Trained models on the same features remain clearly ahead in both studies; the pixel-only variant failed.',
             'Standard models have seen part of the Study B database.',
             'Feature extraction does the perceptual work; this does not show that Jev can watch video.'],
    survey_use='Separate perceptual preprocessing, feature design and the decision model; distinguish zero-shot from supervised baselines.',
    topics=['multimodal', 'evaluation-methodology'],
    stages=['contract', 'use'], method_families=['hosted_service'], applications=['video-quality'],
    model_relationship=['commercial_jev', 'downstream_system'], test_level='model_test',
    model_versions=[dict(model='Jev', version='jev-1.13', note='Patch version not stated.')],
    openness=_o('not_located', 'not_applicable', 'partial', 'not_located', 'no',
                code='Video tooling repositories cited in the paper are not the study’s full reproduction package.',
                data='Study B uses a public database; Study A encodes are described.'),
    locator='Abstract; §§III–VI; Limitations', priority='P1'),
 '2609.24052': dict(
    short_title='Calibrated Decisions at Scale',
    relationship='Uses hosted jev-1.13.0 to code police crash narratives as gated, typed decisions.',
    summary='Formulates narrative coding as gated typed decisions, audits probabilities against coded fields and blinded human judgments, benchmarks two frontier LLMs, and turns calibration into a human-review budget.',
    task='Screen of 499,500 Texas crash narratives (10-question schema); full 27-question coding of 195,857; 2,416 usable blinded human judgments (effective sample ≈ 1,265).',
    datasets=['Texas CRIS crash narratives 2017–2025 (restricted)'],
    baselines=['two frontier LLMs on the same records', 'administrative coded fields'],
    models=['TypeSafe Jev (jev-1.13.0)'],
    main_finding='Against human labels the typed model reached F1 0.908; one frontier model was 0.059 higher and the other indistinguishable. Probabilities ranked well but overstated prevalence; recalibration on the same labels cut calibration error about 3.3×.',
    caveats=['Single region, single model version and single schema.',
             'Recalibration was fitted on labels from the same distribution; it is not a guarantee for new regions or schemas.',
             'Two-decimal output probabilities put a floor on calibration error for rare variables.',
             'Narratives and record-level files are not redistributable; a de-identified audit table is available on request once the data owner confirms.'],
    survey_use='Distinguish administrative codes from narrative-grounded truth, and convert probability reliability into a human-review workload.',
    topics=['calibration', 'selective-control', 'evaluation-methodology', 'efficiency'],
    stages=['probability', 'control', 'use'], method_families=['hosted_service'], applications=['annotation'],
    model_relationship=['commercial_jev', 'downstream_system'], test_level='system_test',
    model_versions=[dict(model='Jev', version='jev-1.13.0', note='Pinned identifier recorded per call.')],
    openness=_o('available', 'not_applicable', 'restricted', 'partial', 'partial',
                code='Schema, asynchronous runner, metric implementations with tests and figure generators are public.',
                code_url='https://github.com/pozapas/jev-calibrated-narrative-coding/blob/850fe4f0db35f165b56247a53d786cd1dfc12302/README.md',
                data='Underlying narratives are not redistributable under the data agreement.',
                predictions='Aggregated outputs are public; the pair-level audit table is available on request pending approval.',
                recomputable='Population-scale results depend on restricted Stage-2 files.'),
    locator='Abstract; §§3–5; Table 6; Data and code availability', priority='P0'),
 '2609.23986': dict(
    short_title='Jev-Mem',
    relationship='Uses hosted Jev as the System-One control plane of an agent memory system; a System-Two LLM writes the answers.',
    summary='Jev decides memory typing and organisation during construction, and query routing, retrieval budget, graph traversal, candidate scoring and stopping during retrieval; an LLM is called only for reasoning and answer synthesis.',
    task='Long-horizon conversational memory on LoCoMo.',
    datasets=['LoCoMo'],
    baselines=['existing agentic memory systems'],
    models=['TypeSafe Jev (version not stated)', 'System-Two LLM'],
    main_finding='LLM-as-a-Judge 0.777 on LoCoMo (+11.0% relative to the strongest baseline), memory construction in 158 s (6.6× faster than the fastest competing system) and 0.93 s average query latency (36.7% lower).',
    caveats=['Each headline number is relative to a different baseline.',
             'Gains belong to the full memory system, not to Jev alone; module-level attribution is needed.',
             'The quality metric is itself an LLM judge; transfer to other datasets is untested.',
             'No Jev model version is pinned.'],
    survey_use='System One decides resources and access; System Two answers. Attribute gains per module rather than reading them as general model superiority.',
    topics=['agents', 'efficiency'],
    stages=['control', 'use'], method_families=['hosted_service'], applications=['agent-memory'],
    model_relationship=['downstream_system', 'commercial_jev'], test_level='system_test',
    model_versions=[dict(model='Jev', version=None, reason='not_reported')],
    openness=_o('available', 'not_applicable', 'available', 'not_located', 'not_assessed',
                code='Repository confirmed; memory/jev_client.py calls system_one (read, not executed).',
                code_url='https://github.com/libingzheren/Jev-Mem/blob/81574eb23f3fd8d1a6c4d54a1e7d6f2dd539e9bb/README.md',
                data='Public benchmark.'),
    locator='Abstract; Experiments; Table 1; memory/jev_client.py', priority='P1'),
 '2609.23959': dict(
    short_title='Open-Jev on CallScreenBench',
    relationship='JevLite: the authors’ own open Jev-style readout on Qwen3-4B with LoRA; not TypeSafe’s model.',
    summary='Fine-tunes Qwen3-4B so that a temperature-scaled softmax over two answer-label logits gives P(scam) after every caller turn, and compares three ways of reading the same fine-tuned decoder.',
    task='41 held-out CallScreenBench scenarios (82 calls, 577 turn-level decisions); synthetic callers; three training seeds.',
    datasets=['CallScreenBench (synthetic calls)'],
    baselines=['LLM judge (MiniMax-M3)', 'fine-tuned ModernBERT-large', 'same Qwen3-4B fine-tuned to generate', 'zero-shot Qwen3-4B'],
    models=['JevLite (Qwen3-4B + LoRA)'],
    main_finding='A three-seed ensemble reached AUROC .974 with calibration error .052, non-inferior to an LLM judge at a pre-registered .02 margin, with no false alarms on legitimate calls and decisions 1.14 turns earlier; 64.5 ms per decision on one consumer GPU, 4.9× faster than the same backbone fine-tuned to generate.',
    caveats=['Recipe selection had test-set exposure (about ten recipes were scored before the selection rule was fixed).',
             'A fine-tuned ModernBERT encoder is not significantly worse; the gain is in readout and calibration, not accuracy.',
             'All callers are synthetic.',
             'Single-model latency and the three-model ensemble quality are measured on different scopes.'],
    survey_use='A same-backbone ablation isolates the readout; judge by false alarms and decision timing, not AUROC alone.',
    topics=['open-models', 'calibration', 'efficiency', 'robustness'],
    stages=['readout', 'probability', 'use'], method_families=['finetuned_decoder'], applications=['fraud-screening'],
    model_relationship=['independent_jev_like'], test_level='model_test',
    model_versions=[dict(model='JevLite', version='paper v1 (three seeds)')],
    openness=_o('not_located', 'not_located', 'not_located', 'not_located', 'no',
                code='No uniquely matching public package located; similarly named OpenJev projects are unrelated.'),
    locator='Abstract; experimental protocol; Table 1; results', priority='P1'),
 '2609.23886': dict(
    short_title='this-that-model-1.0',
    relationship='Open-weight ~2B typed decision model adapted from decider-2b, compared with hosted Jev.',
    summary='Reads the answer from the hidden state at a designated position, restricted to the declared options, and trains with a proper scoring rule; reports local latency, electricity cost and accuracy against hosted systems.',
    task='A 42-family internal suite; a third party’s recorded 68-question cohort (17 states); a released 7,305-question benchmark, of which a 2,250-question subset was answered by every hosted system.',
    datasets=['this-that-spatial-bench (7,305 questions)', 'NanoJev recorded cohort (68 questions)', 'internal 42-family suite (not released)'],
    baselines=['hosted Jev', 'frontier hosted LLMs', 'NanoJev-0.6B'],
    models=['this-that-model-1.0 (~2B)'],
    main_finding='30.9 ms per decision on one laptop GPU; on the 68-question cohort 0.941 accuracy (Brier 0.042) against Jev’s 0.765 (0.133); on the 2,250-question subset 0.844 against Jev’s 0.803.',
    caveats=['The 68-question accuracy gap rests on 12 questions.',
             'The model was trained on the 2,250-question subset’s question shapes; Jev was not.',
             'Electricity-only marginal cost excludes hardware and operations and is not comparable to an API price.',
             'Weaker than strong reasoning models on multi-step arithmetic; on branch-shaped families 0.818 against 0.837–0.968 for hosted models.'],
    survey_use='Local deployment with native restricted readout; compare hardware, training coverage, cost scope and weight availability separately.',
    topics=['open-models', 'efficiency', 'calibration'],
    stages=['readout', 'probability', 'use'], method_families=['finetuned_decoder'], applications=['workflow-decisions'],
    model_relationship=['independent_jev_like'], test_level='model_test',
    model_versions=[dict(model='this-that-model-1.0', version='1.0'), dict(model='Jev (comparison)', version=None, reason='not_reported')],
    openness=_o('available', 'available', 'partial', 'not_located', 'partial',
                code='Inference package and scripts said to reproduce every measurement; thisthat/model.py (restricted softmax) was read.',
                code_url='https://github.com/FLock-io/this-that-model/blob/542d445efa5f68b14bfbd1f8ed25aacd8379d839/README.md',
                weights='Hugging Face flock-io/this-that-model-1.0 (MIT); model API returned 200 on 2026-09-23. The PDF text shows “thisthat-model-1.0”, a line-break artefact.',
                weights_url='https://huggingface.co/flock-io/this-that-model-1.0',
                data='The 7,305-question benchmark is released; the internal suite is not.'),
    locator='Abstract; §§3–4; Table 1; comparison discussion; Availability; thisthat/model.py', priority='P0'),
 '2609.23136': dict(
    short_title='Intent-Driven 6G Edge Orchestration',
    relationship='Hosted Jev interprets service intents into contracts; a deterministic numerical scheduler places the work.',
    summary='Combines live Jev, DeepSeek, Gemini and self-hosted Qwen responses with packet-level New Radio simulation, mobility, shared edge queues and a real image-reading service to ask whether faster contract activation improves timeliness.',
    task='Contract interpretation (locations, deadlines, priorities) for edge orchestration; 12 modeled trajectories per comparison; an image service with 1,080 arrivals per method.',
    datasets=['5G-LENA NR simulation traces', 'image-reading (OCR) service workload'],
    baselines=['DeepSeek', 'Gemini', 'self-hosted Qwen (direct attributes)', 'direct model-selected placement'],
    models=['TypeSafe Jev 1.13'],
    main_finding='With correct interpretation on all evaluated contracts, Jev cut median decision latency by 22.4% against DeepSeek and 61.9% against Gemini. In the real image service over simulated NR access it completed 459 of 1,080 requests correctly and on time, against 463 for DeepSeek and 435 for Qwen.',
    caveats=['Faster decisions did not yield more correct on-time completions than DeepSeek in the image service.',
             'Network access is simulated; the modeled completion gains (+3.50 and +8.35 points) come from simulation.',
             'Same author group and service path as 2609.22753: one study family, not independent replication.'],
    survey_use='Decompose interpretation, network, queueing, scheduling and execution time; check whether decision latency is on the critical path.',
    topics=['efficiency', 'agents'],
    stages=['contract', 'use'], method_families=['hosted_service'], applications=['edge-orchestration'],
    model_relationship=['commercial_jev', 'downstream_system'], test_level='hybrid',
    model_versions=[dict(model='Jev', version='Jev 1.13', note='Patch version not stated.')],
    openness=_o('not_located', 'not_applicable', 'partial', 'not_located', 'no', code='No public code repository confirmed.'),
    study_family_id='li-wang-edge-2026',
    locator='Abstract; real-service results; Fig. and table on 1,080 arrivals', priority='P1'),
 '2609.22753': dict(
    short_title='Replacing LLMs with Jev at the Edge',
    relationship='Hosted Jev replaces a structured-output LLM for bounded intent extraction in an edge service path.',
    summary='Extracts four bounded intent fields with a shared validator, admission policy and scheduler, compares Jev with a matched short structured-output DeepSeek deployment, and measures what caching does to the difference.',
    task='Four bounded intent fields; three consecutive live-API measurement blocks followed by modeled execution; eight paired conditions on a real two-node OCR service.',
    datasets=['live API measurement blocks', 'two-node OCR service workload'],
    baselines=['structured-output DeepSeek', 'self-hosted Qwen', 'rule-based references'],
    models=['TypeSafe Jev (jev-1.13)'],
    main_finding='Jev cut median client decision latency by 15.9–26.5%. Without caching, end-to-end latency on requests both systems completed correctly was 11.1–25.3% lower and API fees per correct completion 69.0–70.6% lower; correct on-time completion matched DeepSeek in 7 of 8 conditions and exceeded it in 1.',
    caveats=['Repeated-request caching largely removes the latency difference.',
             'Results are specific to the measured services, provider regions and time windows.',
             'Same study family as 2609.23136.'],
    survey_use='A deployment-like matched structured-output baseline; compare cost per correct completion rather than price per token.',
    topics=['efficiency', 'structured-output'],
    stages=['contract', 'use'], method_families=['hosted_service', 'generative_adapter'], applications=['edge-orchestration'],
    model_relationship=['commercial_jev', 'downstream_system'], test_level='hybrid',
    model_versions=[dict(model='Jev', version='jev-1.13', note='Patch version not stated.')],
    openness=_o('not_located', 'not_applicable', 'partial', 'not_located', 'no', code='No public code repository confirmed.'),
    study_family_id='li-wang-edge-2026',
    locator='Abstract; execution and caching comparisons; §§ on end-to-end latency and the cache boundary', priority='P1'),
 '2609.25498': dict(
    short_title='Universal Fractal Decision Map',
    relationship='An independent, Jev wire-compatible runtime (werr) with Noul/Choice/Score-style outputs; not TypeSafe research.',
    summary='Proposes a procedural “fractal” decision engine without stored weight tensors and reports speed, accuracy and prompt-injection results on the authors’ own corpus and on a community leaderboard.',
    task='Author corpus of 1,150+ decisions (3,200+ questions); community JevBench submission.',
    datasets=['author corpus (1,150+ decisions)', 'JevBench (community)'],
    baselines=['LLM and neural baselines described by the authors'],
    models=['werr runtime'],
    main_finding='Author-reported 92.6% macro-accuracy (95% CI 90.8–94.1%) on 1,150+ decisions, 7.08 ms median latency on CPU, and a first-place claim on the community JevBench board (81.65%).',
    caveats=['All results are self-reported on the authors’ corpus and infrastructure; the leaderboard claim rests on a community submission.',
             '“0.0% injection bypass” carries a 95% Wilson interval of 0–30.8%: a small sample, not a security guarantee.',
             'The proposed mechanism has not been independently examined.'],
    survey_use='Kept as a boundary case for the scope; not pooled with controlled comparisons.',
    topics=['open-models', 'efficiency', 'robustness'],
    stages=['readout'], method_families=[], applications=['triage'],
    model_relationship=['independent_jev_like'], test_level='model_test',
    model_versions=[dict(model='werr', version=None, reason='not_reported')],
    openness=_o('partial', 'not_applicable', 'partial', 'not_located', 'not_assessed',
                code='Public repository located and its README read; contents not audited.',
                code_url='https://github.com/pCwOrM/werr/blob/2c3138200f1725f0efd8598b8b84729abde67c95/README.md'),
    locator='Abstract; evaluation and claims', priority='P2'),
}


# ---------------------------------------------------------------------------
# 44 background references: purposive seed set for theory and baselines.
# Reading depth for these is metadata + abstract unless stated otherwise.
# (group, role in this survey, topics)
# ---------------------------------------------------------------------------
BACKGROUND = {
 '1810.04805': ('classification', 'Bidirectional encoders are the basic reference point; a natural-language interface does not make conventional classifiers irrelevant.', ['classification']),
 '1909.00161': ('classification', 'Zero-shot text classification with NLI-style label descriptions: historical context for runtime-defined option semantics.', ['classification', 'interface-semantics']),
 '2209.11055': ('classification', 'SetFit: a few-shot discriminative baseline for asking whether convenience comes from the zero-training interface.', ['classification']),
 '2311.08526': ('classification', 'GLiNER: open-type extraction with a bidirectional encoder; related to finite-candidate decisions but a different output task.', ['classification']),
 '2508.07662': ('classification', 'GLiClass: a general lightweight sequence classifier and a direct adjacent baseline for typed decisions.', ['classification', 'open-models']),
 '2412.13663': ('classification', 'ModernBERT: the backbone of several encoder-style open alternatives and a strong lightweight baseline.', ['classification', 'open-models']),
 '2306.07536': ('classification', 'TART: a task-agnostic discriminative reasoning module that predates the product framing.', ['classification']),
 '2503.23303': ('classification', 'SalesRLAgent (2025): domain probabilistic decisions; historically related work that does not establish shared architecture, performance or copying.', ['classification', 'calibration']),
 '2606.22807': ('classification', 'KaLM-Reranker-V1: a reranker whose updated abstract links a Jev model collection; that link does not make it a Jev source paper. Full text spot-checked.', ['classification', 'efficiency']),
 '1706.04599': ('calibration', 'Calibration of modern neural networks and temperature scaling: the post-hoc baseline for any returned probability.', ['calibration']),
 '1906.02530': ('calibration', 'Predictive uncertainty under dataset shift: in-distribution calibration does not transfer to shifted data.', ['calibration', 'robustness']),
 '2207.05221': ('calibration', 'Language models (mostly) know what they know: self-knowledge and confidence expression; native and verbalised confidence differ.', ['calibration']),
 '2302.09664': ('calibration', 'Semantic uncertainty: an alternative definition of confidence for generative models.', ['calibration']),
 '2503.15850': ('calibration', 'Survey of uncertainty quantification and calibration in LLMs: locates the boundary of existing reviews.', ['calibration']),
 '2503.02623': ('calibration', 'Rewarding Doubt: RL for calibrated confidence expression; not an official technical paper of Jev or any open model.', ['calibration']),
 '1705.08500': ('selective', 'Selective classification: risk–coverage and rejection; confidence gating long predates typed decision models.', ['selective-control']),
 '1901.09192': ('selective', 'SelectiveNet: jointly learning prediction and a reject option.', ['selective-control']),
 '2006.01862': ('selective', 'Learning to defer: modelling expert cost jointly with prediction error.', ['selective-control']),
 '2107.07511': ('selective', 'Conformal prediction: finite-sample coverage guarantees and their exchangeability assumptions.', ['selective-control', 'calibration']),
 '2310.05921': ('decision-calibration', 'Conformal decision theory: turning imperfect predictions into constrained decisions.', ['selective-control', 'calibration']),
 '2404.13503': ('decision-calibration', 'Calibration error for decision making: a utility-aware alternative to a single ECE.', ['calibration']),
 '2504.15582': ('decision-calibration', 'Smooth calibration and decision making.', ['calibration']),
 '2511.13699': ('decision-calibration', 'Efficient decision-oriented calibration: a strong post-processing baseline.', ['calibration']),
 '2510.07750': ('decision-calibration', 'Inverse conformal risk control and decision robustness.', ['calibration', 'robustness']),
 '2307.13565': ('decision-calibration', 'Decision-focused learning survey; its optimisation semantics differ from an API returning a choice.', ['calibration']),
 '2109.05093': ('structured-output', 'PICARD: incremental constrained autoregressive decoding, a historical structured-output baseline.', ['structured-output']),
 '2307.09702': ('structured-output', 'Guided generation: valid outputs by construction without solving semantic errors.', ['structured-output']),
 '2411.15100': ('structured-output', 'XGrammar: an efficient constrained-decoding engine for fair generative baselines.', ['structured-output', 'efficiency']),
 '2312.07104': ('structured-output', 'SGLang: shared-prefix reuse and scheduling, whose gains must be separated from decision-head gains.', ['structured-output', 'efficiency']),
 '2501.10868': ('structured-output', 'JSONSchemaBench: structural correctness and efficiency of constrained decoding (title updated on arXiv).', ['structured-output', 'evaluation-methodology']),
 '2604.25359': ('structured-output', 'Structured Output Benchmark: broader task coverage for structured-output quality.', ['structured-output', 'evaluation-methodology']),
 '2607.20492': ('structured-output', 'PhantomFill: when a form demands an answer, models invent one — the closed-set risk of forced choices.', ['structured-output', 'interface-semantics']),
 '2306.05685': ('judging', 'MT-Bench and Chatbot Arena: foundations and biases of LLM-as-a-judge.', ['judging']),
 '2310.08491': ('judging', 'Prometheus: a dedicated evaluator model and a relevant baseline for decision-only judging.', ['judging']),
 '2403.13787': ('judging', 'RewardBench: discriminative reward models as strong judging comparators.', ['judging']),
 '2305.05176': ('routing', 'FrugalGPT: model cascades and cost optimisation have clear precedents.', ['routing', 'selective-control']),
 '2406.18665': ('routing', 'RouteLLM: a learned-routing baseline.', ['routing']),
 '2601.07206': ('routing', 'LLMRouterBench: a unified task set and protocol for routing evaluation.', ['routing', 'evaluation-methodology']),
 '2510.01237': ('routing', 'Confidence-aware routing; an author connection to an open project does not establish shared training, architecture or priority.', ['routing', 'calibration']),
 '2502.17419': ('routing', 'From System 1 to System 2: a reasoning-LLM survey whose terminology predates and is broader than the product.', ['routing']),
 '2503.24377': ('routing', 'Reasoning economy: compare inference budgets, not only parameter counts.', ['routing', 'efficiency']),
 '2309.04992': ('label-robustness', 'Word bias in zero-shot prompt-based classifiers: why option names can become shortcuts.', ['interface-semantics', 'robustness']),
 '2310.11324': ('label-robustness', 'Sensitivity to spurious prompt-format features: a template for order and format invariance tests.', ['interface-semantics', 'robustness']),
 '2608.08254': ('label-robustness', 'Schema descriptions act as prompts: interface validity is not semantic compliance.', ['interface-semantics', 'structured-output']),
}
