"""Repository, relation, source and related-survey curation (cutoff 2026-09-23).

Repository facts come from commit-pinned README snapshots and, where listed,
selected source files read (never executed) during the snapshot audit.
Availability fields describe what this review located; `not_located` is not
evidence that something does not exist.
"""

REPO_TYPES = [
    dict(id='model', label='Model', desc='Releases or describes a typed decision model (weights may or may not be public).'),
    dict(id='adapter', label='Readout / adapter / server', desc='Turns an existing model into typed decisions, or serves a Jev-compatible API.'),
    dict(id='sdk', label='SDK', desc='Client library for a hosted service.'),
    dict(id='system', label='System', desc='An application or research system that uses typed decisions.'),
    dict(id='evaluation', label='Evaluation', desc='An audit or study with its own protocol and results.'),
    dict(id='benchmark', label='Benchmark', desc='A reusable benchmark or leaderboard.'),
    dict(id='project_page', label='Project page', desc='A page and result files, not a full code release.'),
    dict(id='catalogue', label='Catalogue', desc='A curated list or directory (discovery source, not evidence).'),
    dict(id='guide', label='Research guide', desc='An evidence-graded guide or survey draft.'),
]


def R(full_name, rtype, summary, boundary, family=None, base=None, papers=(), affiliation='independent',
      code='available', weights='not_applicable', training='not_located', inference='not_applicable', evaluation='not_located',
      data='not_located', predictions='not_located', notes=None):
    return dict(full_name=full_name, type=rtype, summary=summary, boundary=boundary, method_family=family, base_model=base,
                related_papers=list(papers), affiliation=affiliation,
                availability=dict(code=code, weights=weights, training_code=training, inference_code=inference,
                                  evaluation=evaluation, data=data, raw_predictions=predictions),
                notes=notes)


PRIORITY = [
 R('typesafe-ai/typesafe-sdk-python', 'sdk', 'Official Python client for the TypeSafe API: Choice, Score and Noul questions, synchronous and asynchronous.',
   'An open client does not make the model open; weights and training recipe are not public.', family='hosted_service', affiliation='official (TypeSafe)',
   inference='not_applicable'),
 R('typesafe-ai/typesafe-sdk-js', 'sdk', 'Official TypeScript/JavaScript client for the TypeSafe API with inferred answer types.',
   'Client only.', family='hosted_service', affiliation='official (TypeSafe)'),
 R('typesafe-ai/system-one-adapter-python', 'adapter', 'Official drop-in replacement for the SDK’s system_one call that routes typed questions to OpenAI, Anthropic, Gemini or compatible LLM APIs, for cost, speed and quality comparisons.',
   'Answers and probabilities come from LLM structured output, not from the Jev model; useful as a matched interface baseline.',
   family='generative_adapter', affiliation='official (TypeSafe)', inference='available', notes='src/system_one_adapter/_client.py read.'),
 R('NandhaKishorM/laya', 'model', 'Open, non-autoregressive encoder decision engine: ModernBERT-large (421M) and mmBERT-base (322M) checkpoints with a per-request router; reports 33 ms for one question on a T4.',
   'Public weights and inference code; README comparisons with Jev are self-reported and use different prompts from the vendor’s. Not evidence about Jev’s architecture.',
   family='encoder_head', base='ModernBERT-large; mmBERT-base', weights='available', inference='available', evaluation='partial',
   notes='laya/__init__.py and laya/agent.py read. Background papers 2503.23303 and 2510.01237 list an author name matching the maintainer (identity not verified).'),
 R('jaredpalmer/kev', 'model', 'Small Jev-like decision models (0.8B/4B/9B) on Qwen3.5 with LoRA and an option-pointer readout; training code, frozen evaluation suites and a Jev-compatible local server.',
   'Follows an architecture speculated in a third-party blog post about Jev; that speculation is not a vendor disclosure.',
   family='finetuned_decoder', base='Qwen3.5 (0.8B, 4B, 9B)', weights='available', training='available', inference='available', evaluation='available',
   data='available', notes='kev/model.py read.'),
 R('TheoLeeCJ/SemIf', 'adapter', 'Semantic ifs from frozen open models (formerly “OpenJev”): reads option-token probabilities in one pass, with prefix reuse, MLX/MPS/llama.cpp backends and per-workload temperature calibration.',
   'Reproduces the interface pattern, not Jev’s undisclosed model or training (stated in the README). A natural training-free baseline.',
   family='frozen_decoder_readout', base='frozen Qwen3.5-4B and others', inference='available', evaluation='partial', notes='src/semif_phase1/direct.py read.'),
 R('TianyuCodings/NanoJev', 'model', 'A 0.6B parallel decision model (“nano replica”) with public weights and dataset, trained on game-control decisions (ViZDoom, maze, Snake).',
   'Game-task results do not generalise to a Jev replacement; its recorded hosted-service cohort is reused by 2609.23886.',
   family='finetuned_decoder', base='0.6B decoder', weights='available', data='available', inference='available', evaluation='partial'),
 R('bespokelabsai/nimble', 'model', 'Open recipe and Bespoke-Nimble-9B (LoRA on Qwen3.5-9B) for typed choice and yes/no decisions with candidate scoring; training (2,676) and held-out (324) examples published; temperature refitted on 2026-09-22.',
   'README states it was not distilled from Jev; public scores do not rule out benchmark overlap.',
   family='finetuned_decoder', base='Qwen3.5-9B (LoRA)', weights='available', training='available', inference='available', data='available',
   notes='nimble/scoring/parallel_scorer.py read. GitHub licence field: NOASSERTION.'),
 R('Mapika/decider', 'model', 'One-pass typed decisions (Choice 2–255 options, Score 2–10 levels, Noul) from decoders built on Qwen3.5-2B/4B/35B-A3B; training mixture of public data plus labels from a local Qwen3.5-27B teacher.',
   'Base of this-that-model-1.0; derived checkpoints are not independent methods.',
   family='finetuned_decoder', base='Qwen3.5-2B/4B/35B-A3B', weights='available', training='partial', inference='available'),
 R('FLock-io/this-that-model', 'model', 'this-that-model-1.0 (~1.9–2B): restricted-softmax readout at a designated position; weights on Hugging Face (MIT), inference package and scripts said to reproduce every paper measurement.',
   'Adapted from decider-2b; electricity-only cost figures are not API prices.', family='finetuned_decoder', base='decider-2b (Qwen3.5-2B lineage)',
   papers=['arxiv:2609.23886'], weights='available', inference='available', evaluation='available', data='partial', notes='thisthat/model.py read.'),
 R('nokia-applied-research/AnyJev', 'adapter', 'Turns any open LLM into a Jev-style decider from one prefill of its next-token distribution, with label-free permutation calibration (L0) and label-based calibration (L1).',
   'No corresponding paper located; results are README-reported (e.g. BANKING77, n=300).', family='frozen_decoder_readout', base='any causal LM (Qwen3-8B in README)',
   inference='available', evaluation='partial', notes='anyjev/readout.py and anyjev/calibrate/permute.py read.'),
 R('guanxuyu-sv/Visual-Jev', 'project_page', 'Project page and result JSON for Visual Jev; figures are generated from the result files behind the paper tables.',
   'The full evaluation tree is not in this repository (README); not a full training/inference release.', family='finetuned_decoder',
   base='Qwen3-VL-4B', papers=['arxiv:2609.25845'], code='project_page_only', predictions='partial'),
 R('libingzheren/Jev-Mem', 'system', 'Agent memory system with a Jev System-One control plane, a multi-relational memory plane and a System-Two reasoning plane.',
   'System-level results; module attribution needed.', family='hosted_service', papers=['arxiv:2609.23986'], inference='available',
   notes='memory/jev_client.py read (calls system_one); not executed.'),
 R('pozapas/jev-calibrated-narrative-coding', 'system', 'Replication materials for calibrated crash-narrative coding: schema, asynchronous runner, metrics with tests, figure generators and aggregated outputs.',
   'Narratives and record-level files are not redistributable.', family='hosted_service', papers=['arxiv:2609.24052'],
   evaluation='available', data='restricted', predictions='partial'),
 R('hazemibrahim97/decision-models-css', 'evaluation', 'Replication package for the CSS annotation study: per-call records, analysis scripts and the Jev pilot.',
   'Not re-run by this review.', family='hosted_service', papers=['arxiv:2609.24574'], evaluation='available', data='available', predictions='available',
   notes='pilot_jev.py read.'),
 R('browser-use/jev-ultrafast', 'system', 'Browser agent in which Jev picks an operation and an indexed page element; a small LLM writes text only for TYPE_TEXT.',
   'Text entry and verification still rely on other components; demo timings are system-level.', family='hosted_service', inference='available',
   notes='jev_ultrafast/model.py read.'),
 R('jujumilk3/jev-calibration-audit', 'evaluation', 'Seven API-only experiments (~7,000 calls) on calibration sign, Noul/Choice coherence, order and wording invariance, interference, caching and Korean.',
   'Community report; not peer-reviewed; not re-run. (The 11,759 figure sometimes quoted is the size of a source dataset, not the audit.)',
   evaluation='available', predictions='available'),
 R('scienthoon/jev-ood-calibration', 'evaluation', 'Calibration on 3,721 public-benchmark items and 900 synthetic items whose rule is not recoverable from the text; all raw responses published.',
   'Called through a gateway alias without a model version; temperature refits are post-hoc diagnostics.', evaluation='available', predictions='available', data='available'),
 R('marcosmartinez/jev-acento', 'evaluation', 'Pre-registered audit of jev-1.13.0 on Spanish: 3,200 paired items, 19,200 calls, plus a CLI to rerun on labelled data.',
   'Task- and version-specific; community report.', evaluation='available', predictions='available'),
 R('jourdanlabs/assay-001', 'evaluation', 'Pre-registered calibration and type-safety check on CLINC150 and Banking77 with sealed raw responses (8,576).',
   'Community report; its “independent re-computation” description is not a reproduction by this review.', evaluation='available', predictions='available',
   notes='GitHub licence field: NOASSERTION.'),
 R('instax-dutta/sysone-bench', 'benchmark', 'Head-to-head comparison of Laya and Jev on byte-identical states and questions (751 states, 9 suites per the snapshot audit).',
   'Check option design, baseline fairness and raw data before reusing numbers.', evaluation='available'),
 R('AbdelStark/jev-benchmarks', 'benchmark', 'Probability-aware evaluation harness (calibration, selective risk, resources, latency); first study compares Jev with GLiNER2.5 on BTZSC.',
   'Pilot of 300 held-out examples; statistics need recomputation before citation.', evaluation='available'),
 R('fstandhartinger/jevbench', 'benchmark', 'Community benchmark and leaderboard for Jev-class models (composite of intelligence, calibration, speed and cost).',
   'Submitter-reported numbers and a composite score are not a controlled unified evaluation.', evaluation='available'),
 R('jjd-lab/jev-synthetic-survey', 'evaluation', 'jev-1.13.0 and GPT-4.1 as 300 synthetic questionnaire respondents on Twin-2K-500; compares Noul and Choice framings.',
   '“Survey” means questionnaire, not literature review.', evaluation='available'),
 R('Yifan-Lan/awesome-jev-robustness', 'catalogue', 'Curated tests, calibration audits and failure-mode studies of Jev.',
   'Discovery source; entries must be traced to primary evidence.', notes='Also in the 81-item catalogue audit.'),
 R('LouisUltra/jev-deep-dive', 'guide', 'Evidence-graded deep dive into Jev’s interface and evidence.',
   'A guide, not a systematic review with a documented protocol.', notes='Also in the 81-item catalogue audit.'),
 R('pCwOrM/werr', 'model', 'Jev wire-compatible “zero-memory” decision runtime accompanying the peripheral paper 2609.25498.',
   'Self-reported benchmarks; contested mechanism claims.', papers=['arxiv:2609.25498'], code='partial', notes='README read; contents not audited. GitHub licence field: NOASSERTION.'),
 R('mmastrac/djev', 'adapter', 'Example server for Jev-style structured reads on DiffusionGemma: seeds the answer template, pins positions and reads slot distributions after one denoising step.',
   'Relies on request extensions from vLLM PR #57250; a PR reference is not a merged feature.', family='diffusion_readout', base='DiffusionGemma',
   inference='available'),
 R('razorback16/openjev', 'adapter', 'Open Jev-compatible decision server on DiffusionGemma 26B-A4B via vLLM or MLX, with optional image questions and its own confidence definition.',
   'Independent project; interface differences are documented in the README; not the vendor’s algorithm.', family='diffusion_readout',
   base='DiffusionGemma 26B-A4B', inference='available'),
 R('githubnext/localjev', 'adapter', 'Local Jev-compatible API in TypeScript that asks a model for JSON probabilities, validates, retries and normalises them.',
   'Wire-compatible but not mathematically equivalent to a logit read: probabilities are generated/self-reported (README).',
   family='generative_adapter', base='DiffusionGemma via chat completions', inference='available'),
]

# Reading notes for the 16 priority catalogues (REPOSITORY_REVIEW §2). Others get a generic note.
CATALOGUE_NOTES = {
    'hellogumbo/awesome-jev': 'User-supplied seed catalogue; broad ecosystem entry point, not a paper list or performance evidence.',
    'youzizzz1028/awesome-jev': 'Contains the prior public survey draft “Decisions, Not Tokens”; read in full and compared in docs/related-surveys.md.',
    'omnijev/awesome-jev-gallery': 'Organised by academic threads; its 22 README arXiv IDs are background and do not include the 13 recent core papers.',
    'yifan-lan/awesome-jev-robustness': 'Collects calibration, bias and failure material; useful against success-only selection.',
    'notsointresting/awesome-jev-family': 'Separates models, ports, SDKs and evaluations; useful for family relations after checking primary sources.',
    'louisultra/jev-deep-dive': 'Evidence-oriented guide; a lead, not a protocol-documented review.',
    'heyjunpenn/awesome-jev': 'Large complementary directory with high overlap with the seed.',
    'logicrw/awesome-jev-projects': 'Broad application coverage with many candidates outside the seed.',
    'appitstudio/awesome-jev': 'Many links outside the seed; relation to Jev must be verified per project.',
    'abdelstark/awesome-typesafe-jev': 'Field guide that places official material, evaluations and tools side by side.',
    'cobanov/awesome-jev': 'Mid-sized categorised entry point for cross-checking open models and tools.',
    'yibie/awesome-jev': 'Widely starred community entry point; stars are not a credibility weight.',
    'valentynkit/awesome-jev-typesafe': 'Developer tools, integrations and use cases.',
    'anil-matcha/awesome-jev-by-typesafe': 'Usage-oriented; demos do not establish generalisation.',
    'yzfly/awesome-jev-zh': 'Chinese-language entry point; cite primary sources instead.',
    'mrjev/awesome-jev': 'Another ecosystem list for candidate discovery.',
}

# Relations between works. Types: study_family, companion_repository, derived_from, uses_resources_from,
# evaluates, contrasts_with, depends_on_unmerged, name_collision, author_name_match, prior_survey.
RELATIONS = [
    dict(type='study_family', id='li-wang-edge-2026', members=['arxiv:2609.23136', 'arxiv:2609.22753'],
         note='Same author group (Li, Wang, Gong, Lang, Yu) and related edge service paths; synthesise as one family, not two independent replications.'),
    dict(type='companion_repository', source='arxiv:2609.24574', target='gh:hazemibrahim97/decision-models-css', note='Author replication package cited in the paper.'),
    dict(type='companion_repository', source='arxiv:2609.24052', target='gh:pozapas/jev-calibrated-narrative-coding', note='Data and code availability statement.'),
    dict(type='companion_repository', source='arxiv:2609.23986', target='gh:libingzheren/jev-mem', note='Code link in the abstract.'),
    dict(type='companion_repository', source='arxiv:2609.23886', target='gh:flock-io/this-that-model', note='Availability section.'),
    dict(type='companion_repository', source='arxiv:2609.25845', target='gh:guanxuyu-sv/visual-jev', note='Project page only.'),
    dict(type='companion_repository', source='arxiv:2609.25498', target='gh:pcworm/werr', note='Correspondence link in the paper.'),
    dict(type='derived_from', source='gh:flock-io/this-that-model', target='gh:mapika/decider', note='this-that-model-1.0 is adapted from decider-2b (Apache-2.0), per the paper’s Availability section.'),
    dict(type='uses_resources_from', source='arxiv:2609.23886', target='gh:tianyucodings/nanojev', note='Environment simulator and the recorded hosted-service cohort (68 questions) come from NanoJev (MIT).'),
    dict(type='evaluates', source='arxiv:2609.24574', targets=['gh:nandhakishorm/laya', 'gh:mapika/decider', 'gh:theoleecj/semif', 'gh:bespokelabsai/nimble'], note='Appendix extension to open decision models.'),
    dict(type='evaluates', source='gh:instax-dutta/sysone-bench', targets=['gh:nandhakishorm/laya'], note='Laya vs hosted Jev on byte-identical inputs.'),
    dict(type='contrasts_with', source='gh:githubnext/localjev', target='gh:razorback16/openjev', note='LocalJev states it is wire-compatible but not mathematically equivalent to OpenJev’s logit read.'),
    dict(type='depends_on_unmerged', source='gh:mmastrac/djev', note='Uses request extensions from vLLM PR #57250 (not established as merged).'),
    dict(type='name_collision', term='RLCD', note='TypeSafe’s “Reinforcement Learning for Calibrated Decisions” is unrelated to “RLCD: Reinforcement Learning from Contrastive Distillation” (2023); 2609.24574 makes the same distinction. Neither adjacency implies the same algorithm or copying.'),
    dict(type='name_collision', term='OpenJev', note='Three different things: SemIf (formerly OpenJev, frozen-decoder readout), razorback16/openjev (DiffusionGemma server) and the “Open-Jev” title of 2609.23959 (JevLite).'),
    dict(type='name_collision', term='REFLEX', note='The agent architecture of 2609.26532 is not any community project named “reflex”.'),
    dict(type='name_collision', term='Visual Jev', note='An independent research model (2609.25845), not a TypeSafe release; hosted Jev is text-only.'),
    dict(type='name_collision', term='System One / System 1', note='TypeSafe’s product category borrows Kahneman’s System 1 metaphor; System-1/2 reasoning literature (e.g. 2502.17419) predates and is broader than the product.'),
    dict(type='name_collision', term='survey', note='jjd-lab/jev-synthetic-survey is a questionnaire experiment, not a literature review.'),
    dict(type='author_name_match', members=['arxiv:2503.23303', 'arxiv:2510.01237', 'gh:nandhakishorm/laya'], note='Both papers list “Nandakishor M”, matching the Laya maintainer’s name. Identity was not verified; a shared author would not establish shared architecture, training or priority.'),
    dict(type='prior_survey', source='gh:youzizzz1028/awesome-jev', note='“Decisions, Not Tokens” survey draft dated 21 September 2026; see related-surveys.'),
]

# Official and first-party sources used by the survey (not counted as papers).
SOURCES = [
    dict(id='src:typesafe-launch', title='Introducing System One Models & Jev', publisher='TypeSafe AI', author='Diogo Almeida', date='2026-09-15',
         url='https://typesafe.ai/blog/introducing-system-one-models-and-jev', snapshot='sources/official/launch.txt', accessed='2026-09-23',
         kind='vendor_blog', bibtex_key='typesafe2026launch'),
    dict(id='src:typesafe-docs-models', title='Models (Jev 1.13)', publisher='TypeSafe AI', url='https://docs.typesafe.ai/models',
         snapshot='sources/official/models.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026models'),
    dict(id='src:typesafe-docs-confidence', title='Confidence', publisher='TypeSafe AI', url='https://docs.typesafe.ai/confidence',
         snapshot='sources/official/confidence.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026confidence'),
    dict(id='src:typesafe-docs-system-one', title='System One', publisher='TypeSafe AI', url='https://docs.typesafe.ai/concepts/system-one',
         snapshot='sources/official/concepts__system-one.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026systemone'),
    dict(id='src:typesafe-docs-state', title='State', publisher='TypeSafe AI', url='https://docs.typesafe.ai/concepts/state',
         snapshot='sources/official/concepts__state.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026state'),
    dict(id='src:typesafe-docs-primitives', title='Primitives: Choice, Score and Noul', publisher='TypeSafe AI', url='https://docs.typesafe.ai/primitives',
         snapshot='sources/official/primitives.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026primitives'),
    dict(id='src:typesafe-docs-jaggedness', title='Jev 1.13 jaggedness', publisher='TypeSafe AI', url='https://docs.typesafe.ai/model-jaggedness/jev-1.13',
         snapshot='sources/official/model-jaggedness__jev-1.13.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026jaggedness'),
    dict(id='src:typesafe-docs-routing', title='Confidence-gated routing', publisher='TypeSafe AI', url='https://docs.typesafe.ai/patterns/confidence-routing',
         snapshot='sources/official/patterns__confidence-routing.md', accessed='2026-09-23', kind='vendor_docs', bibtex_key='typesafe2026routing'),
]

# Prior and adjacent surveys. The difference matrix is rendered to docs/related-surveys.md and the site.
RELATED_SURVEYS = [
    dict(id='gh:youzizzz1028/awesome-jev', title='Decisions, Not Tokens: A Survey of Typed, Calibrated, and Machine-Native Decision Models from Classical Classifiers to Jev',
         authors='Anonymous Authors (manuscript); “Awesome Jev contributors” (CITATION.cff)', dated='2026-09-21 (in-text “Full working draft — 21 September 2026”)',
         url='https://github.com/youzizzz1028/Awesome-Jev/blob/f3703012b0034eefe0d59936c44cd33ea11b2990/paper/main.tex',
         commit='f3703012b0034eefe0d59936c44cd33ea11b2990', manuscript_commit='c1347c84a2577ac699fc954fc1b2ef60bd7eb025 (2026-09-21 14:53:42 UTC)',
         checked='2026-09-23: head unchanged since the snapshot (GitHub API).', status='public working draft; CITATION.cff type dataset; no arXiv entry located',
         bib_entries=41, core_ids_cited=0, bibtex_key='decisionsnottokens2026'),
]

SURVEY_MATRIX = [
    # dimension, prior draft (as read at f3703012), this survey (this release), evidence for the comparison
    ('Scope', 'Machine-native decision models broadly, from classical classifiers to Jev; Jev as a contemporary case study.',
     'Jev and finite-option typed decision models: the commercial service, Jev-like implementations and systems that depend on them, with adjacent methods as background.',
     'Prior draft abstract and §2; this survey §1.'),
    ('Cutoff', '21 September 2026 (stated in the draft).', '23 September 2026 (snapshot) plus a same-day incremental rerun (logged).', 'Draft §2.3; data/search-runs.json.'),
    ('Search & screening record', 'Lists databases and keyword families; no query log, hit counts or screening decisions in the repository at the pinned commit (only data/ecosystem.yml and data/resources.yml).',
     '17 logged arXiv queries (225 hits → 197 screened) plus a logged same-day increment; the rejected query kept; background records added by explicit ID are marked; GitHub discovery with page-level logs; single-reviewer screening disclosed.',
     'Draft §2.3 and repository tree at f3703012; research/.'),
    ('Recent empirical coverage', 'None of the 13 core arXiv IDs (2609.22753–2609.26758) appear in its 41-entry bibliography.',
     'Every core and peripheral paper read in full; each claim stored as an evidence record with locator, scope, sample size and model version.', 'Draft references.bib at f3703012; data/claims.json.'),
    ('Model lineage', 'Five-dimensional taxonomy (output contract, inference, learning objective, uncertainty, control); mentions the official adapter.',
     'Six readout families with named open implementations, a derived-from edge (this-that ← decider) and explicit non-equivalence of compatible interfaces.',
     'Draft §5; data/taxonomy.json; data/repositories.json.'),
    ('Failure analysis', 'Conceptual: open-world inputs, local calibration, parallel consistency, compositional safety.',
     'Empirical: option-name rebinding, abstain removal, Noul/Choice incoherence, per-construct confident errors, language shift, quantisation — each tied to a source.',
     'Draft §9; this survey §6.'),
    ('Openness audit', 'Evidence labels A–D (peer-reviewed, preprint, official, community).',
     'Six independent fields per work (code, weights, data, predictions, recomputable, reproduced) and seven per repository.',
     'Draft README; data/papers.json.'),
    ('Recomputability', 'Figures described as conceptual illustrations; no data release for figures.',
     'Every count, table and chart is generated from data/*.json by scripts in the repository; checks run in CI.',
     'Draft Fig. 2 caption; scripts/.'),
    ('Interactive resources', 'GitHub README index and figures.', 'Searchable website with filters, evidence drawers, exports and labelled illustrative explainers.', 'Both repositories.'),
    ('Shared ground', 'Four evaluation layers (validity, semantic correctness, probabilistic reliability, decision utility) and a fair replication protocol.',
     'This survey adopts the same separation and credits the draft for it; the difference lies in the evidence base, not the layering.', 'Draft Table 1 and §8.3.'),
]
