"""Synthesis structures for the first release: failure-mode catalogue and application cards.

Every entry cites claim IDs from claims_2026_09_23.CLAIMS so that the website,
README and manuscript render the same evidence. Wording is editorial; numbers
live only in the claims.
"""

FAILURE_MODES = [
    dict(id='name-binding', title='Option name outweighs the rubric', stage='contract',
         desc='Rebinding which rubric sits behind “no/yes” moves answers far more than the same swap behind neutral names; a 0% type-error rate hides it.',
         claims=['c-26758-hosted-swap', 'c-26758-open-inversion', 'c-26758-type-errors'], mitigation='Neutral identifiers with meaning carried in the rubric; name-invariance checks next to type-error rates.'),
    dict(id='order-vs-binding', title='Order is a different intervention', stage='contract',
         desc='Reordering options and rebinding names test different things: one community audit found no argmax flips under order changes on hosted Jev, while frozen open readouts are order-sensitive until calibrated.',
         claims=['r-calibration-audit', 'r-anyjev'], mitigation='Report order permutation and name rebinding as separate arms.'),
    dict(id='primitive-choice', title='The primitive changes the answer', stage='contract',
         desc='A Noul and a two-option Choice over the same question can disagree, and the choice of primitive can reverse a comparison with an LLM baseline.',
         claims=['r-calibration-audit', 'r-synthetic-survey'], mitigation='Fix the primitive in a protocol; test both when a result depends on it.'),
    dict(id='closed-set', title='Forced choice without an exit', stage='contract',
         desc='When the correct answer is not among the options, a typed model must still choose; removing an abstain option collapsed accuracy on unanswerable items at high confidence.',
         claims=['r-calibration-audit'], mitigation='Include an explicit unknown/abstain option and test with it removed.'),
    dict(id='construct-confidence', title='Confident on the wrong construct', stage='probability',
         desc='Calibration varies by task: on one construct the model was confident while near chance, and audits disagree across datasets.',
         claims=['c-24574-empathy', 'c-24574-ece', 'r-assay-001'], mitigation='Audit reliability per task and construct, not with one global ECE.'),
    dict(id='shift', title='Unknowable rules and distribution shift', stage='probability',
         desc='On labels not recoverable from the text, probabilities stayed concentrated; a large post-hoc temperature was needed to make them honest.',
         claims=['r-ood'], mitigation='Hold out domains and rule changes; recalibrate on target-domain labels.'),
    dict(id='language', title='Language shift costs accuracy', stage='probability',
         desc='A Spanish state with English instructions lost accuracy on every tested dataset; calibration worsened on the hardest tasks.',
         claims=['r-acento', 'v-text-only'], mitigation='Evaluate in the deployment language; pin the model version.'),
    dict(id='quantisation', title='Two-decimal probabilities', stage='probability',
         desc='Probabilities are returned on a 0.01 grid, which puts a floor under calibration error for rare events and can place exactly zero on a correct answer.',
         claims=['c-24052-quantisation', 'r-ood'], mitigation='Treat rare-event probabilities with care; smooth before log-loss.'),
    dict(id='nondeterminism', title='Same request, different answer', stage='readout',
         desc='Repeated identical requests to the hosted model do not always return the same answer, which sets a floor under any flip-rate comparison.',
         claims=['c-26758-retest', 'r-calibration-audit'], mitigation='Measure a test–retest floor and report effects relative to it.'),
    dict(id='format-vs-content', title='Validity effects masquerade as quality', stage='use',
         desc='When comparing with generative baselines, parse failures and repairs change accuracy independently of reasoning; typed outputs remove the failure but not the confound in comparisons.',
         claims=['c-26550-quality'], background=['arxiv:2608.04355'], mitigation='Count invalid outputs as errors and report parse rates separately.'),
    dict(id='hidden-process', title='Right label, wrong quantity', stage='use',
         desc='A wrong intermediate selection can change a derived count while leaving the final label correct.',
         claims=['c-24965-hidden-errors'], mitigation='Score intermediate relations and derived quantities, not only final labels.'),
    dict(id='vendor-boundaries', title='Vendor-listed jagged edges', stage='contract',
         desc='The vendor lists literal reading, arithmetic and counting, date comparison, indirection, large irrelevant state, adversarial content and contradictory criteria as known weaknesses.',
         claims=['v-jaggedness'], mitigation='Keep arithmetic and date logic in code; filter state; split indirect questions.'),
]

APPLICATION_CARDS = [
    dict(id='judging', decides='Which of two responses is better, or whether an answer is supported.', papers=['arxiv:2609.26550'],
         claims=['c-26550-quality', 'c-26550-cascade'], caution='Derivation checking and style-adversarial pairs remain hard; adjudication by one author.'),
    dict(id='annotation', decides='Labels for social-science text and crash narratives, with a probability per label.', papers=['arxiv:2609.24574', 'arxiv:2609.24052'],
         claims=['c-24574-accuracy-cost', 'c-24574-cascade', 'c-24052-f1', 'c-24052-recalibration'], caution='Per-construct failures; recalibration fitted on in-distribution labels.'),
    dict(id='agent-control', decides='Which tool or action to take next inside an agent, escalating to a strong LLM when unsure.', papers=['arxiv:2609.26532'],
         claims=['c-26532-calls', 'c-26532-external'], caution='A cheap generative cascade is competitive where routing is already accurate.'),
    dict(id='agent-memory', decides='How memories are typed, routed, budgeted, traversed and when retrieval stops.', papers=['arxiv:2609.23986'],
         claims=['c-23986-system'], caution='System-level gains with a different baseline per number; LLM-judge metric.'),
    dict(id='scientific-workflow', decides='Which scientific relation governs a calculation that code then performs.', papers=['arxiv:2609.24965'],
         claims=['c-24965-correct-latency', 'c-24965-hidden-errors'], caution='Twenty Choices in ten cases; not discriminative across strong models.'),
    dict(id='video-quality', decides='A quality level from extracted metadata, bitstream and pixel features — never from the video itself.', papers=['arxiv:2609.24395'],
         claims=['c-24395-study-a', 'c-24395-study-b'], caution='Trained models on the same features remain ahead.'),
    dict(id='fraud-screening', decides='Whether a call is a scam, after every caller turn (open JevLite model).', papers=['arxiv:2609.23959'],
         claims=['c-23959-quality', 'c-23959-latency'], caution='Synthetic callers; recipe selected with test-set exposure.'),
    dict(id='edge-orchestration', decides='Bounded intent fields and service contracts for an edge scheduler.', papers=['arxiv:2609.23136', 'arxiv:2609.22753'],
         claims=['c-23136-completion', 'c-22753-e2e-fees', 'c-22753-cache'], caution='One study family; caching largely removes the latency gap.'),
    dict(id='visual-qa', decides='Several forced-choice questions about one image (independent Visual Jev model).', papers=['arxiv:2609.25845'],
         claims=['c-25845-quality', 'c-25845-speed'], caution='Amortized timing; gains concentrated on trained task families.'),
]
